### ISSUE TITLE
NullPointerException in JPEGImageReader.getSourceCSType

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#103]
I get this with the attached (broken) file:
![178360-p1](https://cloud.githubusercontent.com/assets/6665575/6421317/fe50ecec-becd-11e4-863e-910a32d99e69.jpg)

Exception in thread "main" java.lang.NullPointerException
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSourceCSType(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at com.mycompany.preflightmasstest.PreflightMassTest.main(PreflightMassTest.java:27)

An IIOException would be nice :-)

**Comment by haraldk** [comment]
I agree! 

Will fix.

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in 1f990409278453cf5ce51d3cf43bef7a49011a20.

This image is still unreadable, but now fails gracefully with an `IOException`.

-- 
Harald K
