### ISSUE TITLE
EOFException only with twelvemonkeys

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#105]
ImageIO.read(new File("_422364.jpg"));

works fine with the sun reader, but not with twelvemonkeys:

    Exception in thread "main" java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at com.twelvemonkeys.imageio.plugins.jpeg.JFIFSegment.read(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getJFIF(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at JpegMassTest.main(JpegMassTest.java:20)

![_422364](https://cloud.githubusercontent.com/assets/6665575/6449120/cdb26194-c11e-11e4-8407-df0f6d389dc2.jpg)

**Comment by haraldk** [comment]
Interesting... 

A JFIF segment containing only "JFIF\0". 
I'll fix! 

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in d6f90b0b524a003017d35bfc030460618d48a918.

-- 
Harald K
