### ISSUE TITLE
JPEG with ClassCastException

### ISSUE THREAD

**Issue by SamStephens** [haraldk/TwelveMonkeys#1058]
**Describe the bug**

I have a JPEG file that, when you try and read the metadata, has the error `java.lang.ClassCastException: class com.twelvemonkeys.imageio.plugins.jpeg.Unknown cannot be cast to class com.twelvemonkeys.imageio.plugins.jpeg.Application`.

It's unclear to me whether the JPEG is corrupt or not, but I think regardless of whether it is, this is still a bug.

**Version information**

1. The version of the TwelveMonkeys ImageIO library in use.
3.12.0

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
```
openjdk 21.0.5 2024-10-15 LTS
OpenJDK Runtime Environment Corretto-21.0.5.11.1 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.5.11.1 (build 21.0.5+11-LTS, mixed mode, sharing)
```

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

My stack trace is from a unit test for a Gradle based project running on Ubuntu on WSL2.

**To Reproduce**

From a project including com.twelvemonkeys.imageio:imageio-jpeg:3.12.0, run the unit test I provide with my example file available as a resource.

**Expected behavior**

Either the metadata to be provided, or if the JPEG is corrupt, an exception indicating such.

**Example code**
Preferably as a failing JUnit test, or a standalone program with a `main` method that showcases the problem. 

```
    @Test
    public void classCastException() throws Exception {
        ImageReader reader =
                Filter.findImageReader("JPEG", "a suitable JAI I/O image filter is not installed");
        try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream("form10qxz001.jpg");
             ImageInputStream iis = ImageIO.createImageInputStream(inputStream);) {
            reader.setInput(iis);
            IIOMetadata imageMetadata = reader.getImageMetadata(0);
            Node root = imageMetadata.getAsTree("javax_imageio_jpeg_image_1.0");
        }
    }
```

**Sample file(s)**

![form10qxz001](https://github.com/user-attachments/assets/5fd83358-9d8b-4d84-846d-c9455aa2931d)

**Stack trace**

```
java.lang.ClassCastException: class com.twelvemonkeys.imageio.plugins.jpeg.Unknown cannot be cast to class com.twelvemonkeys.imageio.plugins.jpeg.Application (com.twelvemonkeys.imageio.plugins.jpeg.Unknown and com.twelvemonkeys.imageio.plugins.jpeg.Application are in unnamed module of loader 'app')
 at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImage10Metadata.appendMarkerSequence(JPEGImage10Metadata.java:271)
 at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImage10Metadata.getNativeTree(JPEGImage10Metadata.java:114)
 at com.twelvemonkeys.imageio.AbstractMetadata.getAsTree(AbstractMetadata.java:74)
 at convertimagetopdf.ImageToPdfConverterTest.x(ImageToPdfConverterTest.java:123)
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Screenshots**

N/A

**Additional context**

I **think** that the root cause is that the metadata class does not actually have handling for the Unknown segment type (I don't know this code so I could easily be mistaken).

The actual error is from the cast to `com.twelvemonkeys.imageio.plugins.jpeg.Application` in https://github.com/haraldk/TwelveMonkeys/blob/34c9b9b4b51f477a816dda1869db73b5c723e5de/imageio/imageio-jpeg/src/main/java/com/twelvemonkeys/imageio/plugins/jpeg/JPEGImage10Metadata.java#L268-L274

I believe the Unknown segment is created in this default case when reading segments https://github.com/haraldk/TwelveMonkeys/blob/34c9b9b4b51f477a816dda1869db73b5c723e5de/imageio/imageio-jpeg/src/main/java/com/twelvemonkeys/imageio/plugins/jpeg/Segment.java#L97-L98

**Comment by haraldk** [comment]
Thanks for reporting! 

This seems to be a perfectly valid JPEG. It contains a DNL ("define line number") marker. These are so rare I never seen one before in the wild... 

I also think you are right about the code not handling a case it should. I'll create a fix and use your sample file as a test case.

**Comment by haraldk** [comment]
Should be fixed in the latest snapshot. I'll try to make a bug fix release soon.

**Comment by SamStephens** [comment]
Thanks @haraldk , much appreciated.
