### ISSUE TITLE
Fix bug in PICT PixMap reading

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#106]

**Comment by haraldk** [comment]
PICTImageReader incorrectly assumes PixMap has ColorMap;

    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 33024
	at com.twelvemonkeys.imageio.plugins.pict.PICTUtil.readColorTable(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.readOpPackBitsRect(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.readPICTopcodes(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.drawOnto(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.read(Unknown Source)
	at javax.imageio.ImageReader.read(ImageReader.java:940)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.main(Unknown Source)

**Comment by haraldk** [comment]
Fixed in 4839c61f5c57f9b611198c0f30580df37beaa3ed.
