### ISSUE TITLE
EXIFReader may cause OutOfMemoryError for invalid tags

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#110]
Bad EXIFtagId: 0 (INVALID)
    type: 23296 (INVALID)
    count: 1952672112
    /Downloads/jpg/515/515402.jpg
    java.lang.OutOfMemoryError: Java heap space
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readEntry(EXIFReader.java:234)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:95)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readSubdirectories(EXIFReader.java:152)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:121)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readSubdirectories(EXIFReader.java:152)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:121)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.read(EXIFReader.java:83)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readThumbnailMetadata(JPEGImageReader.java:1017)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getNumThumbnails(JPEGImageReader.java:1053)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.main(JPEGImageReader.java:1469)

**Comment by haraldk** [comment]
Fixed in 7ad108ccbade89b0e6309962e50023023d3c90d6.
