### ISSUE TITLE
NegativeArraySizeException when reading image metadata

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#111]
**Update** There doesn't seem to be anything wrong with the image. However, there's something bad happening causing the reader (`JPEGBuffer`) to skip data...

The data in the stream looks like this:

    FF DA 00 08 01 01 01 06 3F 02 0E 70 9A A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 A2 64 05 5D ...

..but the JPEGBuffer class contains:

    FF DA 00 08 A2 A2 A2 A2 A2 64 05 5D 02 87 FC 5B 5C E1 0E BD ...
                *****************??

15 bytes missing..? 

--

It seems `com.sun.imageio.plugins.jpeg.SOSMarkerSegment` doesn't do proper input validation, and might choke on negative component size. Or perhaps the negative component size is just a side effect of a bad read earlier/incorrect offset. The image can be read correctly, but an exception is thrown if one tries to read the image metadata: 

    java.lang.NegativeArraySizeException
	    at com.sun.imageio.plugins.jpeg.SOSMarkerSegment.<init>(SOSMarkerSegment.java:73)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:319)
	    at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1023)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1094)

![182030](https://cloud.githubusercontent.com/assets/110299/6575916/67cba7bc-c733-11e4-85f3-4b3bd5de56db.jpg)

**Comment by haraldk** [comment]
Fixed as part of #113
