### ISSUE TITLE
javax.imageio.metadata.IIOInvalidTreeException: Invalid DHT node

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#112]
Attached image causes exception when trying to read image metadata:

    javax.imageio.metadata.IIOInvalidTreeException: Invalid DHT node
	    at com.sun.imageio.plugins.jpeg.DHTMarkerSegment.<init>(DHTMarkerSegment.java:87)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromMarkerSequenceNode(JPEGMetadata.java:2223)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromNativeTree(JPEGMetadata.java:2208)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromTree(JPEGMetadata.java:2168)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImage10MetadataCleaner.cleanMetadata(JPEGImage10MetadataCleaner.java:261)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1110)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.main(JPEGImageReader.java:1460)

![219251](https://cloud.githubusercontent.com/assets/110299/6574718/b16ed7ce-c727-11e4-9802-171eeb860eb0.jpg)

**Comment by haraldk** [comment]
Fixed in 493edada59a397b85bbcbad2b03820cb0c4bd36d.
