### ISSUE TITLE
javax.imageio.IIOException: Inconsistent metadata read from stream

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#113]
Found another one of the "Inconsistent metadata read from stream" files. We might need to filter out more segments, or just replace the entire metadata with our own implementation.

    javax.imageio.IIOException: Inconsistent metadata read from stream
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:362)
	    at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1023)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1094)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGMassTester.readFile(JPEGMassTester.java:57)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGMassTester.main(JPEGMassTester.java:30)

![229392](https://cloud.githubusercontent.com/assets/110299/6576022/3223f988-c734-11e4-9069-c821fd9b9476.jpg)

**Comment by haraldk** [comment]
The image can be read okay, but the metadata can't be obtained. 

This image is progressive. What makes `JPEGMetadata` look at it as "inconsistent" is that the count of all component selectors in all the SOS segments does not match the count of SOF components. 

SOF components are JFIF standard 1, 2 and 3. Most SOS segments also uses these, however, one segment has a selector value of -16 (..?!). Need to figure out what that means, and how this is affects the decoding. Is it simply ignored?

**Comment by haraldk** [comment]
Nailed it!

There's a bug in `com.sun.imageio.plugins.jpeg.AdobeMarkerSegment` when parsing non-standard length APP14/Adobe segments (i.e. lengths other than 14) that causes the `com.sun.imageio.plugins.jpeg.JPEGBuffer#loadBuf()` method to overwrite parts of the input data (the difference between the real length and 14, at *the end* of the stream). 

The fix seems to be completely ignoring the APP14 segment, and re-inserting it in the metadata later. This might cause some images to be read using raster, that were before read directly using the delegate, but I guess we can live with that.

-- 
Harald K

**Comment by haraldk** [comment]
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6355567

**Comment by haraldk** [comment]
Fixed in e8f207ef546be8acf36471b508ee75b9ea7cabea.
