### ISSUE TITLE
EXIFReader incorrectly tries to read linked subdirectories, causing EOFException and bad tag output

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#114]
TIFF sub-directories are not linked, instead the tag value contains one or more offsets to sub-directories. The current implementation attempts to read linked sub-directories, misinterpreting random data as an IFD pointer, and causing bad tag output like below, and possibly `EOFException` later:

    Bad EXIFtagId: 2 
    type: 32 (INVALID)
    count: 9568256
    0000000c: 0200 2000 0000 9200 0000 0f01 0200 1800 0000 b200 0000 1001 0200 0a00 0000 ca00  .. .............................
    0000002c: 0000 1201 0300 0100 0000 0100 1400 1a01 0500 0100 0000 d400 0000 1b01 0500 0100  ................................
    0000004c: 0000 dc00 0000 2801 0300 0100 0000 0200 1400 3101 0200 0900 0000 e400 0000 3201  ......(...........1...........2.
    0000006c: 0200 1400 0000 ed00 0000 1302 0300 0100 0000 0200 1400 6987 0400 0100 0000 0101  ......................i.........[...]

    java.io.EOFException
	    at javax.imageio.stream.ImageInputStreamImpl.readShort(ImageInputStreamImpl.java:229)
	    at javax.imageio.stream.ImageInputStreamImpl.readUnsignedShort(ImageInputStreamImpl.java:242)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:92)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:113)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readSubdirectories(EXIFReader.java:152)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:121)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readSubdirectories(EXIFReader.java:152)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:121)
	    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.read(EXIFReader.java:83)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readThumbnailMetadata(JPEGImageReader.java:1017)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getNumThumbnails(JPEGImageReader.java:1053)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGMassTester.readFile(JPEGMassTester.java:58)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGMassTester.main(JPEGMassTester.java:30)

**Comment by haraldk** [comment]
Fixed in 7b0414ce788472f9e65327f5d8c74adc33255d5c.

-- 
Harald K
