### ISSUE TITLE
javax.imageio.IIOException: Unsupported element precision

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#115]
Some perfectly readable (although very low quality) images, causes the following exception when trying to access the metadata. The DQT claims to have precision 1 (ie. 16 bit), however the data is not. Should be possible to disregard this and get metadata?

    javax.imageio.IIOException: Unsupported element precision
	    at com.sun.imageio.plugins.jpeg.DQTMarkerSegment$Qtable.<init>(DQTMarkerSegment.java:227)
	    at com.sun.imageio.plugins.jpeg.DQTMarkerSegment.<init>(DQTMarkerSegment.java:61)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:195)
	    at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1023)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1094)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGMassTester.readFile(JPEGMassTester.java:57)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGMassTester.main(JPEGMassTester.java:30)

**Comment by haraldk** [comment]
Fixed in d2d7569a7f2f79ebad8d524874a0614e29422142.
