### ISSUE TITLE
javax.imageio.metadata.IIOInvalidTreeException: componentId attribute out of range

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#117]
javax.imageio.metadata.IIOInvalidTreeException: componentId attribute out of range
	    at com.sun.imageio.plugins.jpeg.MarkerSegment.getAttributeValue(MarkerSegment.java:164)
	    at com.sun.imageio.plugins.jpeg.SOFMarkerSegment$ComponentSpec.<init>(SOFMarkerSegment.java:243)
	    at com.sun.imageio.plugins.jpeg.SOFMarkerSegment.updateFromNativeNode(SOFMarkerSegment.java:149)
	    at com.sun.imageio.plugins.jpeg.SOFMarkerSegment.<init>(SOFMarkerSegment.java:95)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromMarkerSequenceNode(JPEGMetadata.java:2233)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromNativeTree(JPEGMetadata.java:2208)
	    at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromTree(JPEGMetadata.java:2168)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImage10MetadataCleaner.cleanMetadata(JPEGImage10MetadataCleaner.java:261)
	    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1110)

**Comment by haraldk** [comment]
Fixed in 02a427741316eeff8b67bd4d5e11adfed5c1bd34.
