### ISSUE TITLE
java.awt.color.CMMException: LCMS error 13: Couldn't link the profiles

### ISSUE THREAD

**Issue by KoichiSenada** [haraldk/TwelveMonkeys#124]
There appears to be a bug in LCMS in Java 8 in multithreaded lazy loading
[Multithreaded JPEG Image Processing in Java](http://stackoverflow.com/questions/26535842/multithreaded-jpeg-image-processing-in-java)
[JDK-8032243 - LCMS error 13: Couldn't link the profiles](https://bugs.openjdk.java.net/browse/JDK-8032243)
[JDK-8041429 - Parallel read of Different JPG image files (by 2 thread) fails in Java 8](https://bugs.openjdk.java.net/browse/JDK-8041429)

It reproduces both on Linux and Windows in Java 8.
```
C:\>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

My code stack trace with TwevleMonkeys 3.0 JPEGImageReader:
```
Caused by: java.awt.color.CMMException: LCMS error 13: Couldn't link the profiles
        at sun.java2d.cmm.lcms.LCMS.createNativeTransform(Native Method)
        at sun.java2d.cmm.lcms.LCMS.createTransform(LCMS.java:156)
        at sun.java2d.cmm.lcms.LCMSTransform.doTransform(LCMSTransform.java:155)
        at sun.java2d.cmm.lcms.LCMSTransform.colorConvert(LCMSTransform.java:467)
        at java.awt.image.ColorConvertOp.filter(ColorConvertOp.java:571)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
        at javax.imageio.ImageReader.read(ImageReader.java:939)
```

Should we revert back to the **KcmsServiceProvider** instead of **LcmsServiceProvider** or preload some classes or stick with single threads?

**Comment by haraldk** [comment]
I'd report a bug against Oracle/OpenJDK and ask them to raise the priority to something higher than 3/4, because this is a show stopper for many, and can't be worked around (in a reasonable fashion). 

If you can live with single threaded reading (and are able to enforce it), that could work, but I think for now the safest would be to switch back to `KcmsServiceProvider` using:

     -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider


Regards,

-- 
Harald K
