### ISSUE TITLE
exception while reading CMYK image

### ISSUE THREAD

**Issue by savantreddy** [haraldk/TwelveMonkeys#127]
Hi,
am trying to read image using twelvemonkeys jar file, sometimes am getting below exception while reading CMYK images.. please help me to resolve this

    2015-04-04 16:25:53 [DEBUG] (web.FilterChainProxy):305 - /savecanvasimage.do reached end of additional filter chain; proceeding with original chain
    2015-04-04 16:25:53 [DEBUG] (servlet.DispatcherServlet):693 - DispatcherServlet with name 'spring' processing POST request for [/idiocanvas/savecanvasimage.do]
    2015-04-04 16:25:53 [DEBUG] (commons.CommonsMultipartResolver):257 - Found multipart file [file] of size 794254 bytes with original filename [but.jpg], stored in memory
    2015-04-04 16:25:53 [DEBUG] (annotation.DefaultAnnotationHandlerMapping):221 - Mapping [/savecanvasimage.do] to HandlerExecutionChain with handler [com.canvas.controller.CanvasImageController@44d66fce] and 1 interceptor
    2015-04-04 16:25:53 [DEBUG] (support.HandlerMethodInvoker):173 - Invoking request handler method: public java.util.Map com.canvas.controller.CanvasImageController.uploadCanvasPrintImage(javax.servlet.http.HttpServletRequest,org.springframework.web.multipart.MultipartFile)
    2015-04-04 16:25:54 [DEBUG] (commons.CommonsMultipartResolver):280 - Cleaning up multipart file [file] with original filename [but.jpg], stored in memory
    2015-04-04 16:25:54 [DEBUG] (servlet.DispatcherServlet):671 - Could not complete request
    org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/color/ColorSpaces$Profiles
    	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:839)
    	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:312)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:95)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:100)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:79)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:35)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:119)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:187)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:324)
    	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:165)
    	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
    	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    	at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/color/ColorSpaces$Profiles
    	at com.twelvemonkeys.imageio.color.ColorSpaces.getColorSpace(Unknown Source)
    	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageTypes(Unknown Source)
    	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
    	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
    	at javax.imageio.ImageIO.read(Unknown Source)
    	at javax.imageio.ImageIO.read(Unknown Source)
    	at com.canvas.controller.CanvasImageController.commonData2(CanvasImageController.java:174)
    	at com.canvas.controller.CanvasImageController.getFileImageDetails(CanvasImageController.java:133)
    	at com.canvas.controller.CanvasImageController.uploadCanvasPrintImage(CanvasImageController.java:58)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
    	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
    	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)
    	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
    	... 56 more

**Comment by savantreddy** [comment]
platform OS : Windows 7 & CentOS 7 (same issue in both platforms)
 Java runtime : JRE 7, 
Tomcat version : 7
 TwelveMonkeys version : 3.0.2
![but](https://cloud.githubusercontent.com/assets/11816799/7019587/1e5aed38-dd2f-11e4-81a6-87d3be050e23.jpg)

BufferedImage img = null;
img = ImageIO.read(new File(directoryPath + fileSeparator+ fileName));

The issue is not consistent at all times, however sometimes exception raises when i try to read CMYK image after performing read on RGB images for some time.

**Comment by haraldk** [comment]
Thanks!

There's multiple issues here, I think. The image you attached is CMYK, with no ICC profile, which makes the code fall back to a platform dependent "generic" CMYK profile. If that can't be found, it should fall back to a built-in conversion, however this fallback seems to fail for some reason.

Sorry for being persistent, but I'm pretty sure there's an `ExceptionInInitializerError` in there somewhere. 

Also, can you confirm that you are (or not) using the `IIOProviderContextListener` as described?

Can you reproduce the issue locally, without Tomcat? Try running the following command (from a shell/cmd.exe):

    java -cp common-lang-3.0.2.jar:common-io-3.0.2.jar:common-image-3.0.2.jar:imageio-core-3.0.2.jar:imageio-metadata-3.0.2.jar:imageio-jpeg-3.0.2.jar -Dcom.twelvemonkeys.imageio.plugins.jpeg.debug=true -Dcom.twelvemonkeys.imageio.color.debug=true com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader 1e5aed38-dd2f-11e4-81a6-87d3be050e23.jpg 

(fix paths to match your installation, and swap `:` for `;` if on Windows, `1e5aed...` is the image you attached)

This should print some debugging info, about what CMYK profile is used and how it is looked up.

-- 
Harald K

**Comment by savantreddy** [comment]
Hi Harald,
ExceptionInInitializerError : i double checked the log.... but i haven't found any. 

I haven't used  IIOProviderContextListener....
I couldn't reproduce the issue, there are only two instances of this issue over a period of two weeks. Am trying to replicate the issue, no luck. 


Regards,
K

**Comment by haraldk** [comment]
Ok, 

I suggest you try with the `IIOProviderContextListener` and report back if that doesn't fix the problem (note that you have to restart the server after installing the context listener). 

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Feel free to re-open, if the context listener does not fix your issue, or if you have further information.

-- 
Harald K

**Comment by savantreddy** [comment]
Hi,

I believe, the solution provided by you have fixed my issue. we noticed no
issues after placing context listener. I would mail you in case of any
issues, Thanks for your support.

Regards,
Narasimha Reddy

On Wed, Apr 15, 2015 at 3:48 PM, Harald Kuhr <notifications@github.com>
wrote:

> Closing for now. Feel free to re-open, if the context listener does not
> fix your issue, or if you have further information.
>
> Harald K
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haraldk/TwelveMonkeys/issues/127#issuecomment-93304044>
> .
>



-- 
kln

**Comment by haraldk** [comment]
Good stuff! :-)

Appreciate the feedback. 

-- 
Harald K
