### ISSUE TITLE
Cannot read PSD images with PSD Layer Mask data size 28

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#134]
Reading certain PSD files throws exception:

    Exception in thread "main" javax.imageio.IIOException: Illegal PSD Layer Mask data size: 28 (expected 20 or 36)
    	at com.twelvemonkeys.imageio.plugins.psd.PSDLayerMaskData.<init>(Unknown Source)
    	at com.twelvemonkeys.imageio.plugins.psd.PSDLayerInfo.<init>(Unknown Source)
    	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readLayerAndMaskInfo(Unknown Source)
    	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.main(Unknown Source)

Instead, the layer mask data should be correctly parsed or just skipped.

**Comment by haraldk** [comment]
Fixed in 9b71a0cba7c5d6f5a554ec830b8a047d299646bc.

**Comment by haraldk** [comment]
Released in [3.1.1](https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.1.1) (bugfix release).
