### ISSUE TITLE
Unable to conver TIFF to JPG

### ISSUE THREAD

**Issue by kanowins** [haraldk/TwelveMonkeys#155]
Hello,

I'm trying to convert a TIFF to a JPG and I get this error:
```
SEVERE: Invalid argument to native writeImage
javax.imageio.IIOException: Invalid argument to native writeImage
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(Unknown Source)
	at javax.imageio.ImageWriter.write(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(Unknown Source)
	at javax.imageio.ImageIO.doWrite(Unknown Source)
	at javax.imageio.ImageIO.write(Unknown Source)
	at Tiff2JPGTest.convertFile(Tiff2JPGTest.java:48)
	at Tiff2JPGTest.main(Tiff2JPGTest.java:25)
```
I include here the source code of the program, that is pretty simple:
```
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;


public class Tiff2JPGTest {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		try
		{
			if (args.length != 1)
				throw new Exception("Usage: Tiff2JPGTest <source_file>");
				
			String strFile = args[0];
			File f = new File(strFile);
			if (!f.exists())
				throw new Exception("File " + strFile + " doesn't exist");
			
			convertFile(f);
			
			Logger.getLogger(Tiff2JPGTest.class.getName()).info("Done!");
		}
		catch(Throwable e)
		{
			Logger.getLogger(Tiff2JPGTest.class.getName()).log(Level.SEVERE, e.getMessage(), e);
		}

	}
	
	public static void convertFile(File f) throws Exception
	{
		Logger.getLogger(Tiff2JPGTest.class.getName()).info("Reading file " + f.getAbsolutePath());	
		String strFileName = f.getName();
		String strOutputName = strFileName.substring(0, strFileName.lastIndexOf("."));
		File fOutput = new File(f.getParent() + "/" + strOutputName + ".jpg");
						
		BufferedImage image = ImageIO.read(f);
			
		Logger.getLogger(Tiff2JPGTest.class.getName()).info("Output file " + fOutput.getName());
		ImageIO.write(image, "jpg", fOutput);

	}
}
```
Also, you have here the link to the tiff (very small):

http://sumalab.com/test/test.tif

This is happening with the last version (3.2), and tested on java 1.7 and java 1.8 with the same result.

Keep the good work, you are awesome.

Thanks in advance!

**Comment by haraldk** [comment]
Hi,

Have been on summer holiday/vacation, but I'll look into your issue as soon as I'm back! :-)

-- 
Harald K

**Comment by haraldk** [comment]
Closing this, as it's really just a symptom of #25 (missing CMYK JPEG support in the `JPEGImageWriter`). 

-- 
Harald K
