### ISSUE TITLE
NullPointerException when reading JPEG image

### ISSUE THREAD

**Issue by rmuller** [haraldk/TwelveMonkeys#169]
java.lang.NullPointerException:
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getRawImageType(JPEGImageReader.java:763)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getRawImageType(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1400)

![u-vorm-aluminium](https://cloud.githubusercontent.com/assets/754040/9444162/6b6968b6-4a85-11e5-92b5-b2bfc4399093.jpg)

Environment:
Ubuntu 12.04 (x64)
Oracle Java 8u60
TwelveMonkeys 3.1.2

**Comment by haraldk** [comment]
Thanks for reporting!

I'll fix! 


-- 
Harald K

**Comment by haraldk** [comment]
Fixed in e957120.

-- 
Harald K
