### ISSUE TITLE
Unreadable TIFF image

### ISSUE THREAD

**Issue by danieledepetrini** [haraldk/TwelveMonkeys#17]
Hello Harald,

I've tried to load some TIFF but for one I get:

javax.imageio.IIOException: Unsupported TIFF Compression value: 4
        at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(Unknown Source)

Is that a known limitation or a bug?

Thanks,

Daniele.

**Comment by mavarazy** [comment]
Is there a workaround for this?

**Comment by haraldk** [comment]
The latest release has full support for TIFF compression types 3 and 4 (CCITT T.4 and T.6). See #61 

-- 
Harald K

**Comment by julioheitor** [comment]
Hi Harald K,

i am using the imageio-tiff dependency version 3.2 but i am still getting the exception
'javax.imageio.IIOException: Unsupported TIFF Compression value: 4'.

What is the correct version that i must use?

Regards!

**Comment by haraldk** [comment]
@julioheitor Can you please post the full stack trace? You should not get this exception with the latest version.

-- 
Harald K

**Comment by julioheitor** [comment]
@haraldk 

below the exception i've got and the code i have run to test the dependency:

Exception (i printed the tiff reader just to be sure):

reader: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@5f697518

javax.imageio.IIOException: Unsupported TIFF Compression value: 4
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at main.ThumbNailTest.getThumbNail(ThumbNailTest.java:82)
	at main.ThumbNailTest.main(ThumbNailTest.java:49)
Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:228)
	at main.ThumbNailTest.main(ThumbNailTest.java:51)

The source code:

 private static BufferedImage getImage(String filePath) {

    long fileSize = 0;
    long initialTime = System.currentTimeMillis();
    
    
    Iterator<ImageReader> readers = ImageIO.getImageReadersBySuffix("TIF");
    while (readers.hasNext()) {
        System.out.println("reader: " + readers.next());
    }
    
    BufferedImage image = null;
    try {
      File file = new File(filePath);
      fileSize = file.length();
      image = ImageIO.read(file);   //The exception  raises here!
    }
    catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
      return null;
    }

}

**Comment by haraldk** [comment]
@julioheitor I think you have some dependencies wrong. I just downloaded the imageio-tiff-3.2.jar (to be completely sure) and I had no problems reading a TIFF with compression type 4.

Unfortunately, the stack trace above doesn't tell me much, as it has no line numbers (the 3.2 build should have line numbers enables as well, another clue you might be using the wrong version).

The sample file I use below, is the one used in the test cases, and can be found [here](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tiff/src/test/resources/tiff/ccitt/group4.tif).

    $ java -cp common-lang-3.2.jar:common-io-3.2.jar:common-image-3.2.jar:imageio-core-3.2.jar:imageio-metadata-3.2.jar:imageio-tiff-3.2.jar -Dcom.twelvemonkeys.imageio.plugins.tiff.debug=true com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader  imageio/imageio-tiff/src/test/resources/tiff/ccitt/group4.tif 
    Reading using: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@50e0de15
    Byte order: LITTLE_ENDIAN
    Number of images: 1
    IFD 0: IFD[256/ImageWidth: 6 (SHORT), 257/ImageHeight: 4 (SHORT), 258/BitsPerSample: 1 (SHORT), 259/Compression: 4 (SHORT), 262/PhotometricInterpretation: 0 (SHORT), 266/FillOrder: 1 (SHORT), 273/StripOffsets: 8 (LONG), 274/Orientation: 1 (SHORT), 277/SamplesPerPixels: 1 (SHORT), 278/RowsPerStrip: 4 (SHORT), 279/StripByteCounts: 7 (LONG), 284/PlanarConfiguration: 1 (SHORT), 297/PageNumber: [0, 1] (SHORT), 318: [10492471/33554432, 689963/2097152] (RATIONAL), 319: [5368709/8388608, 11072963/33554432, 5033165/16777216, 5033165/8388608, 5033165/33554432, 16106127/268435456] (RATIONAL)]
    [..............................................................................]
    Read time: 12 ms
    image: BufferedImage@7165ae07: type = 12 IndexColorModel: #pixelBits = 1 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@4a8487ba transparency = 1 transIndex   = -1 has alpha = false isAlphaPre = false BytePackedRaster: width = 6 height = 4 #channels 1 xOff = 0 yOff = 0

Whereas, using 3.1.2, I get the same exception as you:

    $ java -cp common-lang-3.1.2.jar:common-io-3.1.2.jar:common-image-3.1.2.jar:imageio-core-3.1.2.jar:imageio-metadata-3.1.2.jar:imageio-tiff-3.1.2.jar -Dcom.twelvemonkeys.imageio.plugins.tiff.debug=true  com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader  imageio/imageio-tiff/src/test/resources/tiff/ccitt/group4.tif 
    Reading using: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@3a204443
    Byte order: LITTLE_ENDIAN
    Number of images: 1
    IFD 0: IFD[256/ImageWidth: 6 (SHORT), 257/ImageHeight: 4 (SHORT), 258/BitsPerSample: 1 (SHORT), 259/Compression: 4 (SHORT), 262/PhotometricInterpretation: 0 (SHORT), 266: 1 (SHORT), 273/StripOffsets: 8 (LONG), 274/Orientation: 1 (SHORT), 277/SamplesPerPixels: 1 (SHORT), 278/RowsPerStrip: 4 (SHORT), 279/StripByteCounts: 7 (LONG), 284/PlanarConfiguration: 1 (SHORT), 297: [0, 1] (SHORT), 318: [10492471/33554432, 689963/2097152] (RATIONAL), 319: [5368709/8388608, 11072963/33554432, 5033165/16777216, 5033165/8388608, 5033165/33554432, 16106127/268435456] (RATIONAL)]
    imageio/imageio-tiff/src/test/resources/tiff/ccitt/group4.tif
    javax.imageio.IIOException: Unsupported TIFF Compression value: 4
    	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(Unknown Source)
       	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.main(Unknown Source)


-- 
Harald K

**Comment by julioheitor** [comment]
@haraldk 

indeed the version was outdated. I just updated to 3.2 and run a mvn eclipse:eclipse and the new version appeared.

But a new error occurred and i think it has to do with java version (i am using the sdk 1.6):
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twelvemonkeys/imageio/plugins/tiff/TIFFImageWriterSpi : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at sun.misc.Service$LazyIterator.next(Service.java:272)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:190)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:121)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:142)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:48)

**Comment by julioheitor** [comment]
I just changed the java version to 1.7_80 and it worked. But i cannot do it because the whole project was compiled with java 1.6 and i have to make it work with it. Do you have any tip?

**Comment by haraldk** [comment]
@julioheitor Please see #198, to not mess up this old issue completely. :-)
