### ISSUE TITLE
failure to load huge JPG file

### ISSUE THREAD

**Issue by gregkotsaftis** [haraldk/TwelveMonkeys#178]
Loaded jars in classpath are:
```
common-image-3.1.2.jar
common-io-3.1.2.jar
common-lang-3.1.2.jar
imageio-batik-3.1.2.jar
imageio-bmp-3.1.2.jar
imageio-core-3.1.2.jar
imageio-jpeg-3.1.2.jar
imageio-metadata-3.1.2.jar
imageio-tiff-3.1.2.jar
```
While trying to load and display [THIS](http://expirebox.com/download/0f73af7876d9c00abeb0f7cf535549a3.html) JPG file, I get a black screen and no exception.
1. If I convert it to a BMP file it loads and displays fine!
2. If I remove `imageio-jpeg-3.1.2.jar` from the classpath, the JPG displays fine!
Is there a problem with the specific file? Is it the size?

**Comment by gregkotsaftis** [comment]
I DO get an exception after all:
```
Could not instantiate SVGImageReader (missing support classes).
java.lang.NoClassDefFoundError: org/apache/batik/transcoder/TranscoderException
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReaderSpi.onRegistration(Unknown Source)
	at javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:726)
	at javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:307)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:211)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at gr.metadata.lib.ui.image.MyImageIO.read(MyImageIO.java:58)
	at gr.metadata.lib.ui.image.ImageHelper.loadImage(ImageHelper.java:226)
	at gr.metadata.orthomed.forms.panels.JP_FolderThumbnails$1.run(JP_FolderThumbnails.java:259)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.batik.transcoder.TranscoderException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

**Comment by gregkotsaftis** [comment]
also a runtime exception for the converted BMP (load and display of the BMP is working) when trying to convert it to JPG via Java:
```
Could not instantiate SVGImageReader (missing support classes).
java.lang.NoClassDefFoundError: org/apache/batik/transcoder/TranscoderException
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReaderSpi.onRegistration(Unknown Source)
	at javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:726)
	at javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:307)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:211)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at gr.metadata.lib.ui.image.MyImageIO.read(MyImageIO.java:58)
	at gr.metadata.lib.ui.image.ImageHelper.loadImage(ImageHelper.java:226)
	at gr.metadata.orthomed.forms.panels.JP_FolderThumbnails$1.run(JP_FolderThumbnails.java:259)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.batik.transcoder.TranscoderException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

**Comment by haraldk** [comment]
Hi,

I tried to load your JPEG file, but had no problem doing so... But as you say, the image is quite large. Are you sure you have a large enough heap to decode and display it? I needed somewhere between 512m and 1g here. The JPEG decoding requires a bit more memory than BMP, so that might explain why it would load as a BMP.

The stack trace you see is because you have the TwelveMonkeys `imageio-svg.jar` on class path, but are missing the required Batik libraries. It's completely unrelated to the JPEG not being displayed. To fix it, either add the Batik JARs (there's quite a few of them), or remove the SVG plugin from class path.


Best regards,

-- 
Harald K

**Comment by gregkotsaftis** [comment]
yes, I have 1GB heap; when loading the BMP it just uses about 500MB or that. I will try with the svg addon an see what happens.

**Comment by gregkotsaftis** [comment]
wait! i do not have `imageio-svg.jar` in my classpath! I do not use SVG at all!

**Comment by haraldk** [comment]
Sorry,

My bad, the JAR is named `imageio-batik.jar`. It contains the SVG plugin.

-- 
Harald K

**Comment by gregkotsaftis** [comment]
Thanks a LOT!
Indeed it was the mem; it seems 1GB was too little!
I used x64 JDK and 2GB of heap and it worked like a charm!
Also, I got rid of the svg exception after removing the jar.

**Comment by haraldk** [comment]
Great stuff!

The memory usage is crazy, it shouldn't really need more than roughly 250 MB to display this image... But unfortunately, the way I intercept the JPEG loading, means I need at least twice that ammount. And then Java2D probably adds more weight for acceleration of the `BufferedImage`. 

PS: I can read it fine here using `-Xmx720m` (720 MB heap, anything less causes `OutOfMemoryError`), but your application may be doing more, and thus needs more memory. 


Best regards,

-- 
Harald K

**Comment by gregkotsaftis** [comment]
yes, my app is a little heavier.
still I wonder did ImageIO's original JPEG loader managed to load that file without any more memory requirements...

**Comment by haraldk** [comment]
Well, 

As I said, unfortunately, the way I intercept the JPEG loading, means I need at least twice that amount (ie. two times the memory needed by the default JPEGImageReader) in some situations. Unfortunate, but expected.

I always get an `OutOfMemoryError` here if I don't have enough memory... Maybe if you send the exact code you are using (as a full compilable/runnable sample) I could reproduce it? I don't swallow any exceptions in the code, but maybe things could go bad if you run out of memory in the native code. 

-- 
Harald K

**Comment by gregkotsaftis** [comment]
you are right; I cannot reproduce the "black screen" and no "out of memory error" anymore.
there must have been an uncaught app error (out of memory) before the "black screen" and i missed it...
I verified your memory requirement with this small [test] (http://expirebox.com/download/e7e471f4ddf3f7b21ee08a6f3834e9da.html).
