### ISSUE TITLE
Can't build imageio-tiff

### ISSUE THREAD

**Issue by OSwoboda** [haraldk/TwelveMonkeys#187]
-------------------------------------------------------------------------------
Test set: com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxEncoderStreamTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.242 sec <<< FAILURE! - in com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxEncoderStreamTest
testReencodeImages(com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxEncoderStreamTest)  Time elapsed: 0.241 sec  <<< ERROR!
java.io.FileNotFoundException: H:\tmp\test.tif (Das System kann den angegebenen Pfad nicht finden)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxEncoderStreamTest.testImage(CCITTFaxEncoderStreamTest.java:163)
	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxEncoderStreamTest.testReencodeImages(CCITTFaxEncoderStreamTest.java:124)

**Comment by haraldk** [comment]
Ouch.

Sorry about the inconvenience!

Not sure how that got in there, and even weirder, it passes with no problems on OS X and Travis... 

I'll have a fix right away.


-- 
Harald K

**Comment by haraldk** [comment]
Fixed.

-- 
Harald K
