### ISSUE TITLE
Bogus marker length when reading JPEG image

### ISSUE THREAD

**Issue by tecywiz121** [haraldk/TwelveMonkeys#274]
I get an exception when trying to open a specific JPEG image, and I am not entirely sure why. I suspect it has something to do with the metadata attached to it.

Here's the image: [Metadata_BogusMarkerLength.jpg.tar.gz](https://github.com/haraldk/TwelveMonkeys/files/374081/Metadata_BogusMarkerLength.jpg.tar.gz)

The exception:

```
Caused by: javax.imageio.IIOException: Bogus marker length
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:481)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:602)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.getRawImageType(JPEGImageReader.java:759)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getRawImageType(JPEGImageReader.java:272)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:343)
        at javax.imageio.ImageReader.read(ImageReader.java:939)
        ... 81 more
```

I get the following output from exiv2 (not sure if it's relevant):

```
Error: Upper boundary of data for directory Panasonic, entry 0x00a7 is out of bounds: Offset = 0x00003086, size = 864, exceeds buffer size by 56 Bytes; truncating the entry
Error: Offset of directory Panasonic, entry 0x2003 is out of bounds: Offset = 0x000033e6; truncating the entry
Error: Offset of directory Panasonic, entry 0x8010 is out of bounds: Offset = 0x000033fa; truncating the entry
Error: XMP Toolkit error 203: Duplicate property or field node
Warning: Failed to decode XMP metadata.
File name       : 11-905-4519-0-01.jpg
File size       : 63723 Bytes
MIME type       : image/jpeg
Image size      : 960 x 960
Camera make     : Panasonic
Camera model    : DMC-GF6
Image timestamp : 2016:02:12 11:09:37
Image number    : 
Exposure time   : 1/15 s
Aperture        : F3.5
Exposure bias   : -233/100 EV
Flash           : No, compulsory
Flash bias      : 0
Focal length    : 14.0 mm (35 mm equivalent: 28.0 mm)
Subject distance: 
ISO speed       : 400
Exposure mode   : Auto
Metering mode   : Spot
Macro mode      : Off
Image quality   : High
Exif Resolution : 960 x 960
White balance   : Auto
Thumbnail       : None
Copyright       : 
Exif comment    : 
```

**Comment by haraldk** [comment]
Hi,

Thanks for reporting! 

I can reproduce the exception, and (at first glance) it seems the JPEG is corrupt (contains a bad marker segment length). But as other software can read this JPEG, it should be possible to create a workaround that can read it. 

I'll investigate further when I find the time.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Seems that the library is to blame... :-O 

There's a bug in the code that downsamples the 16 bit DQT to 8 bit (this is needed for the metadata to work).

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in latest master.
