### ISSUE TITLE
Build fails with OpenJDK on Linux

### ISSUE THREAD

**Issue by ksclarke** [haraldk/TwelveMonkeys#283]
Similar to https://github.com/haraldk/TwelveMonkeys/issues/33 the build from master fails for me when my JDK is set for OpenJDK but works when my JDK is set for OracleJDK.

    kevin@kevin-oryx:~/Workspace/TwelveMonkeys$ java -version
    openjdk version "1.8.0_91"
    OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
    OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
    
    kevin@kevin-oryx:~/Workspace/TwelveMonkeys$ mvn -version
    Apache Maven 3.3.9
    Maven home: /usr/share/maven
    Java version: 1.8.0_91, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "4.4.0-38-generic", arch: "amd64", family: "unix"

Build output:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.twelvemonkeys.imageio.plugins.jpeg.JFXXThumbnailReaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 sec - in com.twelvemonkeys.imageio.plugins.jpeg.JFXXThumbnailReaderTest
Running com.twelvemonkeys.imageio.plugins.jpeg.EXIFThumbnailReaderTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec - in com.twelvemonkeys.imageio.plugins.jpeg.EXIFThumbnailReaderTest
Running com.twelvemonkeys.imageio.plugins.jpeg.JFIFThumbnailReaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.twelvemonkeys.imageio.plugins.jpeg.JFIFThumbnailReaderTest
Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGProviderInfoTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.twelvemonkeys.imageio.plugins.jpeg.JPEGProviderInfoTest
Running com.twelvemonkeys.imageio.plugins.jpeg.FastCMYKToRGBTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec - in com.twelvemonkeys.imageio.plugins.jpeg.FastCMYKToRGBTest
Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriterTest
Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.079 sec <<< FAILURE! - in com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriterTest
testWrite(com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriterTest)  Time elapsed: 0.034 sec  <<< FAILURE!
java.lang.AssertionError: Invalid argument to native writeImage
	at org.junit.Assert.fail(Assert.java:91)
	at com.twelvemonkeys.imageio.util.ImageWriterAbstractTestCase.testWrite(ImageWriterAbstractTestCase.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGImage10MetadataCleanerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.twelvemonkeys.imageio.plugins.jpeg.JPEGImage10MetadataCleanerTest
Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStreamTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStreamTest
Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg/cmyk-sample.jpg image 0: Inconsistent metadata read from stream
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg/cmyk-sample-multiple-chunk-icc.jpg image 0: Image format Error
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg/0x00-to-0xFF-between-segments.jpg image 0: Image format error
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg/jfif-bogus-empty-jfif-segment.jpg image 0: Inconsistent metadata read from stream
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg/jfif-16bit-dqt.jpg image 0: Unsupported element precision
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg-lossless/8_ls.jpg image 0: Unsupported JPEG process: SOF type 0xc3
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg-lossless/16_ls.jpg image 0: Unsupported JPEG process: SOF type 0xc3
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg-lossless/24_ls.jpg image 0: Unsupported JPEG process: SOF type 0xc3
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg-lossless/testimg_rgb.jpg image 0: Unsupported JPEG process: SOF type 0xc3
WARNING: Reading reference metadata failed for TestData: file:/home/kevin/Workspace/TwelveMonkeys/imageio/imageio-jpeg/target/test-classes/jpeg-lossless/testimg_gray.jpg image 0: Unsupported JPEG process: SOF type 0xc3
WARNING: Test skipped due to reader.getRawImageType(0) returning null
Tests run: 122, Failures: 2, Errors: 0, Skipped: 4, Time elapsed: 4.648 sec <<< FAILURE! - in com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest
testThumbnailInvertedColors(com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest)  Time elapsed: 0.002 sec  <<< FAILURE!
org.junit.ComparisonFailure: RGB values differ expected:<#ff[efd5c4]> but was:<#ff[db738e]>
	at org.junit.Assert.assertEquals(Assert.java:123)
	at com.twelvemonkeys.imageio.util.ImageReaderAbstractTest.assertRGBEquals(ImageReaderAbstractTest.java:1616)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest.assertRGBEquals(JPEGImageReaderTest.java:1007)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest.testThumbnailInvertedColors(JPEGImageReaderTest.java:794)

testGetTypeSpecifiers(com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: ImageTypeSepcifier from getRawImageType should be in the iterator from getImageTypes
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at com.twelvemonkeys.imageio.util.ImageReaderAbstractTest.testGetTypeSpecifiers(ImageReaderAbstractTest.java:1272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Failed tests: 
  JPEGImageReaderTest>ImageReaderAbstractTest.testGetTypeSpecifiers:1272 ImageTypeSepcifier from getRawImageType should be in the iterator from getImageTypes
  JPEGImageReaderTest.testThumbnailInvertedColors:794->assertRGBEquals:1007->ImageReaderAbstractTest.assertRGBEquals:1616 RGB values differ expected:<#ff[efd5c4]> but was:<#ff[db738e]>
  JPEGImageWriterTest>ImageWriterAbstractTestCase.testWrite:130 Invalid argument to native writeImage

Tests run: 183, Failures: 3, Errors: 0, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Twelvemonkeys ...................................... SUCCESS [  0.707 s]
[INFO] TwelveMonkeys :: Common ............................ SUCCESS [  0.019 s]
[INFO] TwelveMonkeys :: Common :: Language support ........ SUCCESS [  3.373 s]
[INFO] TwelveMonkeys :: Common :: IO ...................... SUCCESS [  2.914 s]
[INFO] TwelveMonkeys :: Common :: Image ................... SUCCESS [  1.891 s]
[INFO] TwelveMonkeys :: Servlet ........................... SUCCESS [  3.190 s]
[INFO] TwelveMonkeys :: ImageIO ........................... SUCCESS [  0.012 s]
[INFO] TwelveMonkeys :: ImageIO :: Core ................... SUCCESS [  0.861 s]
[INFO] TwelveMonkeys :: ImageIO :: Metadata ............... SUCCESS [  1.604 s]
[INFO] TwelveMonkeys :: ImageIO :: Photoshop Path Support . SUCCESS [  1.435 s]
[INFO] TwelveMonkeys :: ImageIO :: BMP plugin ............. SUCCESS [  1.480 s]
[INFO] TwelveMonkeys :: ImageIO :: HDR plugin ............. SUCCESS [  1.815 s]
[INFO] TwelveMonkeys :: ImageIO :: ICNS plugin ............ SUCCESS [  0.739 s]
[INFO] TwelveMonkeys :: ImageIO :: IFF plugin ............. SUCCESS [  1.151 s]
[INFO] TwelveMonkeys :: ImageIO :: JPEG plugin ............ FAILURE [  5.373 s]
[INFO] TwelveMonkeys :: ImageIO :: PCX plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PDF plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PICT plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PNM plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PSD plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: SGI plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: TGA plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Thumbs.db plugin ....... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: TIFF plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Batik Plugin ........... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: reference test cases ... SKIPPED
[INFO] TwelveMonkeys :: Contrib ........................... SKIPPED
[INFO] TwelveMonkeys :: BOM ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
When I switch to OracleJDK though, the build completes successfully.

```
kevin@kevin-oryx:~/Workspace/TwelveMonkeys$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

kevin@kevin-oryx:~/Workspace/TwelveMonkeys$ mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-38-generic", arch: "amd64", family: "unix"
```

**Comment by haraldk** [comment]
Hi Kevin,

I had the same issues trying to set up automatic builds on Travis for OpenJDK. I ended up just disabling it for now, and go with the OracleJDK build.

There seems to be issues related to both color matching and the native code of the JPEG plugin. The different color matching is really a problem of OpenJDK, so the tests will never pass, unless there's special code to handle the differences. I haven't been able to look further into the JPEG problem.

Unfortunately, I don't have the time and resources to prioritize this right now. But if you would like to dig into it, I'd be very happy to accept a fix/workaround. :-)


Best regards,

-- 
Harald K

**Comment by ksclarke** [comment]
Hi Harold, yes, I completely understand since it works on Oracle's. I might have the time to investigate further. I also just wanted to note it in case someone else came across the problem and didn't realize using Oracle was a workaround.

**Comment by gustavo-belduma** [comment]
Those people who still have the problem, check the following post:
[bit.ly/3ekmTZ7](https://bit.ly/3ekmTZ7)

It is solved using Oracle JDK
