### ISSUE TITLE
BMPImageReader.getImageMetadata throws exception for files with incorrect header

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#285]
BMPImageReader.getImageMetadata() throws exception for certain non-spec BMPs that reports 24 bit palette, but don't actually contain palette data. 

See http://stackoverflow.com/questions/39983471/bmp-filenot-correctly-read-by-android

Stack trace:

    java.lang.IllegalArgumentException: Map size (0) must be >= 1
        at java.awt.image.IndexColorModel.<init>(IndexColorModel.java:419)
        at com.twelvemonkeys.imageio.plugins.bmp.BMPImageReader.readColorMap(BMPImageReader.java:170)
        at com.twelvemonkeys.imageio.plugins.bmp.BMPImageReader.getImageMetadata(BMPImageReader.java:645)

**Comment by haraldk** [comment]
Fixed in 17eeda2.
