### ISSUE TITLE
Multi-page tiff files

### ISSUE THREAD

**Issue by jorgeflorez** [haraldk/TwelveMonkeys#291]
Hello,
I am trying to read a multi-page tiff file (I do not know much about that format). when I use 
`imageio-tiff 3.2.1`
I get this exception
`java.io.EOFException
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:353)
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:405)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readValue(EXIFReader.java:363)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readValueAt(EXIFReader.java:283)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readEntry(EXIFReader.java:273)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:108)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:127)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:127)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:127)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:127)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:127)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:127)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.read(EXIFReader.java:87)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readMetadata(TIFFImageReader.java:171)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getNumImages(TIFFImageReader.java:259)
	at com.flowerz.tifftest.Test.test2(Test.java:95)
	at com.flowerz.tifftest.Test.main(Test.java:56)`

When I use JAI
`jai-imageio-core 1.3.1`
the program runs and extracts some pages, not all,  and then I get 
`javax.imageio.IIOException: I/O error reading image metadata!
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.readMetadata(TIFFImageReader.java:331)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.seekToImage(TIFFImageReader.java:301)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.prepareRead(TIFFImageReader.java:962)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1160)
	at com.flowerz.tifftest.Test.test2(Test.java:98)
	at com.flowerz.tifftest.Test.main(Test.java:56)
Caused by: java.io.EOFException
	at javax.imageio.stream.ImageInputStreamImpl.readInt(ImageInputStreamImpl.java:251)
	at javax.imageio.stream.ImageInputStreamImpl.readUnsignedInt(ImageInputStreamImpl.java:266)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFIFD.initialize(TIFFIFD.java:303)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageMetadata.initializeFromStream(TIFFImageMetadata.java:109)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.readMetadata(TIFFImageReader.java:327)
	... 5 more`

I would like to know if there is a way to check if the tiff file is "valid", or should I just catch the exception.

Thanks

**Comment by jorgeflorez** [comment]
I just wrote a similar program (extracting the images) using c# and I got no errors. All images were extracted. Now I am not sure if the file is valid or just the Java libraries have some error.

**Comment by Schmidor** [comment]
It could be an error of the libraries, but it could also be that your c# library is just more tolerant.
Could you try if it works with TwelveMonkeys 3.3 or attach the file if it doesn't?

**Comment by jorgeflorez** [comment]
Hi, thank you for your response. 
I just changed the dependency and used 3.3 version with no luck.
`java.io.EOFException
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:353)
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:405)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readValue(EXIFReader.java:367)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readValueAt(EXIFReader.java:287)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readEntry(EXIFReader.java:277)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:109)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(EXIFReader.java:133)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.read(EXIFReader.java:87)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readMetadata(TIFFImageReader.java:176)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getNumImages(TIFFImageReader.java:264)
	at com.flowerz.tifftest.Test2.test2(Test2.java:41)
	at com.flowerz.tifftest.Test2.main(Test2.java:16)`
This is the code I use:
[Test2.txt](https://github.com/haraldk/TwelveMonkeys/files/578993/Test2.txt)
Inside the zip file you will find one of the tiff files I am having problems.
[Ipc.zip](https://github.com/haraldk/TwelveMonkeys/files/579005/Ipc.zip)

Thanks.

**Comment by Schmidor** [comment]
The second page conains an entry with the TagId 32934, which has a pointer to somewhere after the EOF.
I'm not sure what this tag should contain. From the look of a similar tag on the first page it could contain TIFF annotations.
As the TiffTag points to an invalid location it is an error on the file.

Is it ok if we use the file for unit tests and add it to the repository?

@haraldk Catching EOFExceptions at EXIFReader.readValueAt() and returning null would make the file readable. If thats ok I'll make a pull request ready.

**Comment by jorgeflorez** [comment]
The images I am handling are kindda confidential. But I think the information there is not that relevant. Use it for tests :)

**Comment by haraldk** [comment]
Thanks for looking into this!

I don't have a problem with the proposed fix, but we need to find a way to report the problem to clients of the library. If we start catching exceptions like this, we might end up with an incomplete IFD that makes it impossible for the TIFFImageReader to decode the image. And we no longer know/have access to the source of the problem. 

So I'm thinking of introducing some sort of WarningListener to the metadata package. Implementations can then delegate to their ImageReader's warning listener. 

I'll update when I'm back home. :-)


-- 
Harald K

**Comment by haraldk** [comment]
Okay,

Have verified that @Schmidor 's quick fix works, applying something similar as in interim fix. Adding listener support later.

-- 
Harald K
