### ISSUE TITLE
Not a JPEG file error

### ISSUE THREAD

**Issue by dickyj** [haraldk/TwelveMonkeys#302]
Hi,
I am using your plugin and I encountered a NOT a JPEG file error as well, I am using the 3.3.1 branch. 
Here is the file, it opens well in the browser.
http://www.hongkongairport.com/eng/img/shopping/dining/photo/photo_jade.jpg

Any clues what is causing it? Thx

**Comment by haraldk** [comment]
Hi,

Can you please attach the code you use and the stack trace you get?

I can read the file without problems here, using 3.3.1. 

-- 
Harald K

**Comment by dickyj** [comment]
Harald,
Thanks for the reply. Here is the code.


```
import java.awt.Dimension;
import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;
import java.util.Iterator;

import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.spi.ImageReaderSpi;
import javax.imageio.stream.ImageInputStream;

import org.apache.commons.lang3.StringUtils;

import com.sun.imageio.plugins.jpeg.JPEGImageReader;



public class ImageIOUtil {
	
   protected static final ImageReaderSpi provider = lookupSpi();

   private static ImageReaderSpi lookupSpi() {
       try {
           return (ImageReaderSpi) Class.forName("com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi").newInstance();
       }
       catch (InstantiationException | IllegalAccessException | ClassNotFoundException e) {
           // assumeNoException(e);
       }

       return null;
   }	

	public static final Dimension getImageInfo(String urlPath, int imgWidthStyle, int imgHeightStyle)
			throws IOException {
		if (imgWidthStyle > 0 && imgHeightStyle > 0) {
			if (imgWidthStyle < 150 && imgHeightStyle < 150) {
				// skip checking via HTTP
				return new Dimension(imgWidthStyle, imgHeightStyle);
			}
		}

		URL url = new URL(urlPath);
		URLConnection urlConn = url.openConnection();
		urlConn.setRequestProperty("User-Agent",
				"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4; en-US; rv:1.9.2.2) Gecko/20100316 Firefox/3.6.2");

		ImageInputStream in = null;
		try {
			in = ImageIO.createImageInputStream(urlConn.getInputStream());
			final Iterator readers = ImageIO.getImageReaders(in);
			if (readers.hasNext()) {
				ImageReader reader = (ImageReader) readers.next();
				try {
					reader.setInput(in);
					return new Dimension(reader.getWidth(0), reader.getHeight(0));
				} finally {
					reader.dispose();
				}
			}
			return null;
		} catch (IOException e) {
			if (StringUtils.containsIgnoreCase(e.getMessage(), "Invalid icc profile")) {
				JPEGImageReader reader = (JPEGImageReader) provider.createReaderInstance();
				reader.setInput(ImageIO.createImageInputStream(urlConn.getInputStream()));
				return new Dimension(reader.getWidth(0), reader.getHeight(0));				
				
			} else {
				throw e;
			}
		} finally {
			if (in != null)
				in.close();
		}
	}

	public static void main(String[] args) throws Exception {
		Dimension dim = getImageInfo("http://www.hongkongairport.com/eng/img/shopping/dining/photo/photo_jade.jpg", 0, 0);

		System.out.println("Dim width " + dim.getWidth() + ", height " + dim.getHeight());

	}
}
```

**Comment by haraldk** [comment]
...and the full stack trace? 

-- 
Harald K

**Comment by dickyj** [comment]
Oh right, here it is:

```
Exception in thread "main" javax.imageio.IIOException: Not a JPEG file: starts with 0x6b 0x32
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:481)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:602)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getWidth(JPEGImageReader.java:716)
	at server.co.intrafeed.service.url.ImageIOUtil.getImageInfo(ImageIOUtil.java:67)
	at server.co.intrafeed.service.url.ImageIOUtil.main(ImageIOUtil.java:79)
```

Line 79 is here:
```
			if (StringUtils.containsIgnoreCase(e.getMessage(), "Invalid icc profile")) {
				JPEGImageReader reader = (JPEGImageReader) provider.createReaderInstance();
				reader.setInput(ImageIO.createImageInputStream(urlConn.getInputStream()));
			>>Line 79 =>	return new Dimension(reader.getWidth(0), reader.getHeight(0));				
				
			} else {
				throw e;
			}
```

**Comment by haraldk** [comment]
Thanks.

If you look carefully at your code, you'll find that you explicitly create an instance of `com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi` in this case. You can also see from the stack trace that there is absolutely no mention of `com.twelvemonkeys` anything in your stack trace. In other words, you are not really using the library...

Running the following command with the dependencies from 3.3.1 produces the expected output:

    $ java -cp  <truncated-for-brevity> ImageIOUtil
    Dim width 546.0, height 314.0

As I said, I also had no problem reading and displaying the `"photo_jade.jpg"` JPEG file locally. So, I'm pretty sure this is just a class path issue at your side (the plugin is missing from the class path at runtime). 

For further instructions on how to set up and trouble-shoot the installation, please read [Installing](https://github.com/haraldk/TwelveMonkeys#installing).


Best regards,

-- 
Harald K

**Comment by dickyj** [comment]
Ok, it WORKS now, thanks for creating this superb library. Apparently, I did not include the correct plugins in maven.
