### ISSUE TITLE
Re-encoding a CCITT compressed TIFF may cause ClassCastException

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#312]
In the case of re-encoding a CCITT compressed TIFF, with metadata from the original, the G3/G4 options may not be a long value as the writer expects, thus causing a ClassCastException.

See #310 for background and sample images.

Full stack trace:

    Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
    at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.createCompressorStream(TIFFImageWriter.java:578)
    at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.writePage(TIFFImageWriter.java:430)
    at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.writeToSequence(TIFFImageWriter.java:975)

Easily fixed by changing the line in question to:

    option = ((Number) entries.get(compression == TIFFExtension.COMPRESSION_CCITT_T4 ? TIFF.TAG_GROUP3OPTIONS : TIFF.TAG_GROUP4OPTIONS).getValue()).longValue();

**Comment by haraldk** [comment]
Fixed in 6ea1ea8.
