### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by megglos** [haraldk/TwelveMonkeys#316]
Hi,

seems like imageIO is suffering from a GIF-bug not getting any attention since 3 years.

I wondered whether it might be possible adding GIF support to twelveMonkeys to tackle these issues? It kind of correlates with the main purpose of extended format support :)

https://bugs.openjdk.java.net/browse/JDK-7132728

Thanks!
Sebastian

**Comment by haraldk** [comment]
Hi Sebastian,

I wasn't aware of this bug, but then again GIF isn't a format that I use frequently... 

It would be nice to have a GIF plugin as part of the library (if it would be better than the JRE one), but to be honest, I don't think it will happen unless someone contributes the code, or at least provide a good starting point. I'm quite busy fixing bugs in the existing plugins, and adding support for completely different formats, which I think may be more relevant.

Fixing the bug in the LZW decoding doesn't seem to be too hard (I haven't looked at the actual code, but I do have my own LZW encoder/decoder as part of the TIFF plugin, which should behave quite similarly), so perhaps just fixing it and submitting it to the OpenJDK project would be a better option?


-- 
Harald K

**Comment by megglos** [comment]
Thanks for the fast response! :)
Yeah, seems more reasonable to fix the issue at the jdk source. I'll get in touch with the openjdk guys.

**Comment by eolivelli** [comment]
JDK ImageIO GIT reader is really slow for large gifs, and it wants to load metadata even when not used, I see hotspots  with stacktraces like this:
```

   java.lang.Thread.State: RUNNABLE
        at com.sun.imageio.plugins.gif.GIFImageReader.concatenateBlocks(GIFImageReader.java:641)
        at com.sun.imageio.plugins.gif.GIFImageReader.readMetadata(GIFImageReader.java:749)
        at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:863)
        at javax.imageio.ImageIO.read(ImageIO.java:1448)
```

**Comment by haraldk** [comment]
@eolivelli There might be room for improvements in the JRE GIF plugin, both in efficiency and performance. 

But I wouldn't worry about reading metadata, as some of it *is needed* (image offsets, dimensions, local color table, etc.) for GIF decoding.

I have started creating a GIF plugin based on existing sources, but it's not a high priority to finish it, as of now. If there is an urgent need for it, do you perhaps have some spare time and/or funding to invest in the development?

Best regards,

-- 
Harald K

**Comment by eolivelli** [comment]
@haraldk to me it would be quite important, that concatenateBlocks is wasting memory and CPU while doing a lot of memory copies. I have a GIF file (provided by a customer) which consumes too much resources.
Can you give me some pointer to the new implementation ? I can ask for DEV resources in my company (me or one of my collegues)

**Comment by haraldk** [comment]
The current code is based on Kevin Weiner/FM Software's GIFDecoder/AnimatedGifEncoder (version 1.03). You'll find plenty of variations on the net, I can't remember exactly which one I used as a starting point. In any case, the header of the files states:

> No copyright asserted on the source code of this class. May be used for any purpose, however, refer to the Unisys LZW patent for restrictions on use of the associated LZWEncoder class.  [...]

I'll try to make my current work available as a separate branch at some point (I have wrapped them in `ImageReader/ImageWriter` implementations, and made them work with `ImageInputStreams` etc). But the main decoding is the same. In the mean time, have a look and see if the mentioned classes have potential. 


Best regards,

-- 
Harald K

**Comment by eolivelli** [comment]
I think I am already using AnimatedGifEncoder in some application but as you are stating it is not compatible with ImageIO. So having a single API to use will be great.

I will be happy to see your branch and hopefully find resources to help you

Thank you
