### ISSUE TITLE
Unable to process PSB Files

### ISSUE THREAD

**Issue by mjayprateek** [haraldk/TwelveMonkeys#318]
I'm receiving this error while reading a PSB file using TwelveMonkeys PSD plugin:

````
java.awt.image.RasterFormatException: Incorrect scanline stride: 208608
	at sun.awt.image.ByteComponentRaster.verify(ByteComponentRaster.java:901)
	at sun.awt.image.ByteComponentRaster.<init>(ByteComponentRaster.java:201)
	at sun.awt.image.ByteInterleavedRaster.<init>(ByteInterleavedRaster.java:191)
	at sun.awt.image.ByteInterleavedRaster.<init>(ByteInterleavedRaster.java:113)
	at java.awt.image.Raster.createWritableRaster(Raster.java:980)
	at java.awt.image.Raster.createWritableRaster(Raster.java:941)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1073)
	at com.twelvemonkeys.imageio.ImageReaderBase.getDestination(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:357)
````

Is this a known issue?

**Comment by haraldk** [comment]
Hi,

Thanks for reporting! No, this isn't a known issue, although the scanline stride value 208608 seems quite large... What are the dimensions of your image?

Are you using the latest (currently 3.3.1) release?

Can you please attach a PSB file which cause the issue? I need this, as I have a quite small selection of PSB files for testing.

Also, if the exception can't be reproduced simply using `ImageIO.read(..)`, please attach a small test case or code sample that can. 

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi,

If you have trouble attaching the PSB sample file to the issue tracker, here are some options:

* Rename the file to .png before uploading (I'll rename it back)
* Upload the image to dropbox or similar, and share a download link in the issue
* If you can't share the image publicly, you can, as a last resort, email it to me personally

I will need a sample file that reproduces the issue, to be able to investigate this issue further. If not, I'll close the issue for now in a few days (but you are of course free to re-open, as soon as a sample file is provided). 


Best regards,

-- 
Harald K
