### ISSUE TITLE
Invalid component ID 1 in SOS when reading CMYK JPEG

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#323]
```
    javax.imageio.IIOException: Invalid component ID 1 in SOS
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:481)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:602)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1059)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readRaster(JPEGImageReader.java:1458)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readRaster(JPEGImageReader.java:920)
	at org.apache.pdfbox.filter.DCTFilterProd.decode(DCTFilterProd.java:104)
```

![huhu2](https://cloud.githubusercontent.com/assets/6665575/22998049/65f519f2-f3d5-11e6-9a9f-168e6a4d10e7.jpg)

I'm using 3.3.2 on 1.8.0_121 on Windows 7.

(memo for myself: in 200818.pdf)

**Comment by haraldk** [comment]
Hi Tilman,

Thanks for reporting!

I'll look into this. It seems from initial testing that the SOF contains duplicate ids (two components with id 1). Not sure why the native code chokes on this when reading the SOS, though... 

Looks okay in Chrome, so it should be fixable. :-)

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in latest master.

The reader now tries to resolve duplicate component ids in SOF/SOS segments.

-- 
Harald K
