### ISSUE TITLE
ArrayIndexOutOfBoundsException in CCITTFaxDecoderStream.decode2D

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#328]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 25
	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decode2D(CCITTFaxDecoderStream.java:184)
	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decodeRowType6(CCITTFaxDecoderStream.java:275)
	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decodeRow(CCITTFaxDecoderStream.java:287)
	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.fetch(CCITTFaxDecoderStream.java:114)
	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.read(CCITTFaxDecoderStream.java:439)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1508)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:934)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at TwelveMonkeysTest.main(TwelveMonkeysTest.java:57)


```

[223423.zip](https://github.com/haraldk/TwelveMonkeys/files/803948/223423.zip)

This file comes from a stream in a PDF file, I constructed the TIF header myself. The PDF file displays properly in Adobe Reader, ghostscript and in PDF.js.

I tried to change the offending code line to do nothing if the index is out of bounds and that works, but I don't know if this the best solution.

Unrelated and unimportant: I looked at the changes since we copied the code from CCITTFaxDecoderStream.java - why does getNextChangingElement() declare a "throws IOException"? I can't see where this would be thrown.

**Comment by haraldk** [comment]
Thanks for reporting! 

Seems to be an issue here, and I agree we should handle this. Need to look into this in a bit more depth, to figure out what would be the best way...
@Schmidor Do you have time to look at this?

Just a quick question though... What color do you expect the lower 1/4th of the image to be? Windows PhotoViewer thinks it should be solid black. After making sure we don't get out of bounds, the TIFFImageReader thinks it should be solid white... 

Re: getNextChangingElement(), I agree, IOException can't be thrown in that context, and can safely be ignored/removed. 

-- 
Harald K

**Comment by THausherr** [comment]
I wonder if I messed up the tiff header... something looks cut off, but when I display the raw stream in PDFBox the image is full. Here's another file and this one isn't cut off.

[223423-2.zip](https://github.com/haraldk/TwelveMonkeys/files/804358/223423-2.zip)

**Comment by haraldk** [comment]
Ah,

Thanks. This one looks better (with my interim fix). Now it's a fixed, ordered b/w pattern covering the entire area.

-- 
Harald K

**Comment by Schmidor** [comment]
@haraldk Did you find out what the problem is or should I still have a look at it?

**Comment by haraldk** [comment]
@Schmidor  I created an interim fix locally that works for the supplied file. But I didn't really spend any time on understanding the algorithm, so I don't know if it's a general solution. You're the CCITT expert. ;-)

Here's my "fix": 
[CCITTFaxDecoderStream_AIOOBE.zip](https://github.com/haraldk/TwelveMonkeys/files/821501/CCITTFaxDecoderStream_AIOOBE.zip)

-- 
Harald K

**Comment by Schmidor** [comment]
I've analysed the CCITT data and your fix would work, but I would prefer changing the array lengths for changesReferenceRow / changesCurrentRow from  columns+1 to columns+2, as that should be faster than additional IFs and also fix this. The data is only producing one more "change" than expected. 

With a possible change from white to black before the first column we expect a maximum of columns+1 changes per line, which would be 25 for this image as it is changed for every column with black on the first and the "ending" change after the last column.
This image uses H-Mode for every change and has 26 changes for the first line which is uncommon:
"H0w1b, H1w1b, ....., H1w0b"
I believe our writer would use V-Modes for the last changes and produce 25 changes as expected. :)

**Comment by haraldk** [comment]
Great stuff!

My quick-fix just tried to get rid of the exception. You analysis and fix sounds a lot better and more correct to me. Seems to work fine!

I'll create a fixed based on your suggestion and add Tilman's image as a test case for both the `CCITTFaxDecoderStream` and the `TIFFImageReader`, as soon as possible.

Thank you!

-- 
Harald K

**Comment by haraldk** [comment]
Fixed using @Schmidor's suggestion. Many thanks.

-- 
Harald K

**Comment by THausherr** [comment]
Thanks both!
