### ISSUE TITLE
mvn package - test failure - testGetTypeSpecifiers - OpenJDK/LCMS

### ISSUE THREAD

**Issue by csyperski** [haraldk/TwelveMonkeys#33]
I can't seem to get a successful build on Ubuntu 14.04 or Fedora 20, I am getting the same failed tests, if this normal?  Am I doing something wrong?

Java -version
java version "1.7.0_51"
OpenJDK Runtime Environment (fedora-2.4.4.1.fc20-x86_64 u51-b02)
OpenJDK 64-Bit Server VM (build 24.45-b08, mixed mode)

export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=256m"
mvn -e package

tail of mvn output:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest
WARNING: Reading reference metadata failed for TestData: file:/home/csyperski88/Downloads/TwelveMonkeys-master/imageio/imageio-jpeg/target/test-classes/jpeg/cmyk-sample.jpg image 0: Inconsistent metadata read from stream
WARNING: Reading reference metadata failed for TestData: file:/home/csyperski88/Downloads/TwelveMonkeys-master/imageio/imageio-jpeg/target/test-classes/jpeg/cmyk-sample-multiple-chunk-icc.jpg image 0: Image format Error
WARNING: Test skipped due to reader.getRawImageType(0) returning null
Tests run: 95, Failures: 2, Errors: 0, Skipped: 3, Time elapsed: 5.806 sec <<< FAILURE!
Running com.twelvemonkeys.imageio.plugins.jpeg.JFIFThumbnailReaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec
Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStreamTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec
Running com.twelvemonkeys.imageio.plugins.jpeg.JFXXThumbnailReaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running com.twelvemonkeys.imageio.plugins.jpeg.EXIFThumbnailReaderTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec
Running com.twelvemonkeys.imageio.plugins.jpeg.FastCMYKToRGBTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.061 sec
Running com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriterTest
Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.09 sec <<< FAILURE!

Results :

Failed tests:   testGetTypeSpecifiers(com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest): ImageTypeSepcifier from getRawImageType should be in the iterator from getImageTypes
  testSetDestinationType(com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderTest): Could not read file:/home/csyperski88/Downloads/TwelveMonkeys-master/imageio/imageio-jpeg/target/test-classes/jpeg/cmm-exception-adobe-rgb.jpg with explicit destination type javax.imageio.ImageTypeSpecifier$Interleaved@2a0e3919
  testWrite(com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriterTest): Invalid argument to native writeImage

Tests run: 138, Failures: 3, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Twelvemonkeys ..................................... SUCCESS [0.254s]
[INFO] TwelveMonkeys :: Common ........................... SUCCESS [0.007s]
[INFO] TwelveMonkeys :: Common :: Language support ....... SUCCESS [1.937s]
[INFO] TwelveMonkeys :: Common :: IO ..................... SUCCESS [3.161s]
[INFO] TwelveMonkeys :: Common :: Image .................. SUCCESS [1.671s]
[INFO] TwelveMonkeys :: Servlet .......................... SUCCESS [3.851s]
[INFO] TwelveMonkeys :: ImageIO .......................... SUCCESS [0.007s]
[INFO] TwelveMonkeys :: ImageIO :: Core .................. SUCCESS [0.644s]
[INFO] TwelveMonkeys :: ImageIO :: Metadata .............. SUCCESS [0.671s]
[INFO] TwelveMonkeys :: ImageIO :: ICO plugin ............ SUCCESS [1.023s]
[INFO] TwelveMonkeys :: ImageIO :: ICNS plugin ........... SUCCESS [0.730s]
[INFO] TwelveMonkeys :: ImageIO :: IFF plugin ............ SUCCESS [1.522s]
[INFO] TwelveMonkeys :: ImageIO :: JPEG plugin ........... FAILURE [6.178s]
[INFO] TwelveMonkeys :: ImageIO :: PDF plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PICT plugin ........... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PSD plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Thumbs.db plugin ...... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: TIFF plugin ........... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Batik Plugin .......... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: JMagick Plugin ........ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: reference test cases .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.981s
[INFO] Finished at: Mon Jan 27 08:59:19 CST 2014
[INFO] Final Memory: 29M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project imageio-jpeg: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/csyperski88/Downloads/TwelveMonkeys-master/imageio/imageio-jpeg/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project imageio-jpeg: There are test failures.

Please refer to /home/csyperski88/Downloads/TwelveMonkeys-master/imageio/imageio-jpeg/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/csyperski88/Downloads/TwelveMonkeys-master/imageio/imageio-jpeg/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:87)
	at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary(SurefirePlugin.java:641)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:615)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:137)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :imageio-jpeg

**Comment by haraldk** [comment]
Should be fixed as part of #41 (commit 94ed531fb284d824e6edbd40b3eb406366fe790f).

-- 
Harald K
