### ISSUE TITLE
Support for Batik 1.9

### ISSUE THREAD

**Issue by boris-petrov** [haraldk/TwelveMonkeys#351]
When using `Apache Batik 1.9` with `imageio-batik`, the following exception occurs:

```
java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration
    at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
    at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.<init>(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParser(Unknown Source)
    at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:428)
    at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:357)
    at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:225)
    at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:300)
    at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:114)
    at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
    at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.init(SVGImageReader.java:547)
    at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.getDefaultWidth(SVGImageReader.java:560)
    at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader.getWidth(SVGImageReader.java:227)
    at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader.paramsToHints(SVGImageReader.java:167)
    at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader.read(SVGImageReader.java:118)
    at javax.imageio.ImageIO.read(ImageIO.java:1448)
```

Can you update TwelveMonkeys to support `Batik 1.9`?

**Comment by haraldk** [comment]
Hi Boris,

I tried to change the Batik dependencies to version 1.9 (and `xmlgraphics-commons` to 2.2) and ran all the tests. They seem to run just fine.

Your stack trace seems to indicate a Xerces configuration issue, most likely caused by a class path issue in your application (could be multiple versions of the "same" JAR, or multiple class loaders having different versions of the JAR), according to what I found after some quick googling of the exception. Exactly how to resolve this, probably depends on your run-time environment (ie. standalone application, app server or other container based deployment), but start by looking at the class path. 

StackOverflow seems to have some useful answers. 


Best regards,

-- 
Harald K

**Comment by boris-petrov** [comment]
Thanks for the quick response!

We are using `xom` in our project for XML processing. It is the only thing that includes `xerces` (I ran `gradle my-project:dependencies` to check that). After excluding `xercesImpl` from `xom`, everything seems to work fine. And there is no `xerces` in the dependencies anywhere. I'm not sure what's going on and what XML parser is used. Do you have any idea why `xom's` `xerces` might have been a problem? I'll be closing the issue, thanks for the support!

**Comment by haraldk** [comment]
No problem!

Sorry, no, I don't use XOM. But I know that XML parser APIs are notoriously painful when it comes to conflicting versions and multiple dependencies, as they are so often used by various 3rd party libraries...

Glad you made it work!

-- 
Harald K
