### ISSUE TITLE
java.io.IOException: Broken pipe with GlassFish 4.1 

### ISSUE THREAD

**Issue by PashaTurok** [haraldk/TwelveMonkeys#355]
Sorry for not very exact title but I don't know what is the problem. So, I use twelvemonkeys with GF4.1 web - profile.
This is my web.xml
```
<web-app>
  ...
    <listener>
        <display-name>ImageIO service provider loader/unloader</display-name>
        <listener-class>com.twelvemonkeys.servlet.image.IIOProviderContextListener</listener-class>
    </listener>
</web-app>
```
This is part from pom.xml
```
<dependency>
    <groupId>com.twelvemonkeys.imageio</groupId>
    <artifactId>imageio-tiff</artifactId>
    <version>3.3.2</version> 
</dependency>
<dependency>
    <groupId>com.twelvemonkeys.servlet</groupId>
    <artifactId>servlet</artifactId>
    <version>3.3.2</version> 
</dependency>
```
This is the code
```
   HttpServletResponse response = ....
   ImageIO.write(image.getImage(),image.getExtension(),response.getOutputStream());
```
This is what I get

```
java.io.IOException: Connection is closed
	at org.glassfish.grizzly.nio.NIOConnection.assertOpen(NIOConnection.java:432)
	at org.glassfish.grizzly.http.io.OutputBuffer.flush(OutputBuffer.java:735)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:291)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:275)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:175)
	at javax.imageio.stream.FileCacheImageOutputStream.close(FileCacheImageOutputStream.java:238)
	at javax.imageio.ImageIO.write(ImageIO.java:1580)
	at me.pavel.freereader.controllers.AjaxController.previewImage(AjaxController.java:104)
	at me.pavel.freereader.controllers.AjaxController$Proxy$_$$_WeldClientProxy.previewImage(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at me.pavel.freereader.webfw.AbstractFrontController.processDynamicRequest(AbstractFrontController.java:167)
	at me.pavel.freereader.webfw.AbstractFrontController.processRequest(AbstractFrontController.java:148)
	at me.pavel.freereader.webfw.AbstractFrontController.doGet(AbstractFrontController.java:214)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.glassfish.grizzly.nio.transport.TCPNIOUtils.flushByteBuffer(TCPNIOUtils.java:149)
	at org.glassfish.grizzly.nio.transport.TCPNIOUtils.writeCompositeBuffer(TCPNIOUtils.java:87)
	at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:129)
	at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:106)
	at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:260)
	at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:169)
	at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:71)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleWrite(TCPNIOTransportFilter.java:126)
	at org.glassfish.grizzly.filterchain.TransportFilter.handleWrite(TransportFilter.java:191)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:111)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:890)
	at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:858)
	at org.glassfish.grizzly.http.io.OutputBuffer.flushBuffer(OutputBuffer.java:1029)
	at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:681)
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:355)
	at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:342)
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:161)
	at javax.imageio.stream.FileCacheImageOutputStream.flushBefore(FileCacheImageOutputStream.java:255)
	at javax.imageio.stream.ImageInputStreamImpl.flush(ImageInputStreamImpl.java:825)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.write(TIFFImageWriter.java:210)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	at javax.imageio.ImageIO.write(ImageIO.java:1578)
	... 39 more
]]

```
Is the problem in twelvemonkeys, my code or GF? Note - I don't get any errors when I work with jpg or png files.

**Comment by haraldk** [comment]
Hi,

I believe this is just a normal condition that happens whenever the client (web browser) closes or aborts the request while it's being processed. I guess it can also happen due to network errors. 

Do you always get this exception when trying to write a TIFF? Or do you just see this randomly in the server logs?

I don't think this is a problem with either GlassFish, TwelveMonkeys or your (server) code. But it's strange it does not happen for JPEG or PNG. What kind of client is consuming your web service? Perhaps it doesn't support TIFF, and doesn't bother to download it?


Best regards,

-- 
Harald K

**Comment by PashaTurok** [comment]
Hi! It seems to be browser problem. I use Firefox 47.0 and it seems that Firefox doesn't support tiff files and doesn't bother to download it. So the issue can be closed. Thanks.

**Comment by haraldk** [comment]
Excellent,

Thanks for your feedback! 

-- 
Harald K
