### ISSUE TITLE
imageio-batik: java.lang.NoClassDefFoundError: org/apache/batik/transcoder/TranscoderException

### ISSUE THREAD

**Issue by tholu** [haraldk/TwelveMonkeys#367]
I want to use `imageio-batik`. What am I doing wrong?

```
Could not instantiate SVGImageReader (missing support classes).
java.lang.NoClassDefFoundError: org/apache/batik/transcoder/TranscoderException
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReaderSpi.onRegistration(SVGImageReaderSpi.java:171)
	at javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:726)
	at javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:307)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:211)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
```

I added this to my pom.xml:

```
<properties>
  <batik.version>1.8</batik.version>
</properties>
...
<dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-batik</artifactId> <!-- svg -->
      <version>3.3.2</version>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-rasterizer-ext</artifactId>
      <version>${batik.version}</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-extensions</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-extension</artifactId>
      <version>${batik.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>xmlgraphics-commons</artifactId>
      <version>2.0.1</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-anim</artifactId>
      <version>${batik.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-svggen</artifactId>
      <version>${batik.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-transcoder</artifactId>
      <version>${batik.version}</version>
      <scope>provided</scope>

      <!--
      There seems to be some weirdness in the
      Batik/FOP poms (Batik depends on FOP 0.20-5) that screws things up,
      making everything end up depending on Batik 1.5, not 1.6
      -->
      <exclusions>
        <exclusion>
          <groupId>fop</groupId>
          <artifactId>fop</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

Is there a working example for using `imageio-batik` with Maven?

**Comment by tholu** [comment]
Nevermind, I'm dumb - I copied the needed dependencies from the pom.xml of `imageio-batik` and forgot to remove the `<scope>provided</scope>` from each!

The dependencies should look like that:

```
<dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-batik</artifactId> <!-- svg -->
      <version>3.3.2</version>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-rasterizer-ext</artifactId>
      <version>${batik.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.xmlgraphics</groupId>
          <artifactId>batik-extensions</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-extension</artifactId>
      <version>${batik.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>xmlgraphics-commons</artifactId>
      <version>2.0.1</version>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-anim</artifactId>
      <version>${batik.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-svggen</artifactId>
      <version>${batik.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>batik-transcoder</artifactId>
      <version>${batik.version}</version>

      <!--
      There seems to be some weirdness in the
      Batik/FOP poms (Batik depends on FOP 0.20-5) that screws things up,
      making everything end up depending on Batik 1.5, not 1.6
      -->
      <exclusions>
        <exclusion>
          <groupId>fop</groupId>
          <artifactId>fop</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

Perhaps put this example in the README, so people can get started easily with `imageio-batik`.
