### ISSUE TITLE
Problem reading tiff file 

### ISSUE THREAD

**Issue by soshianet** [haraldk/TwelveMonkeys#381]
Hello,
I couldn't read tif file, it got error....

````
Exception in thread "main" java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageReaderSpiBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at readImage.Image.main(Image.java:22)
Caused by: java.lang.ClassNotFoundException: com.twelvemonkeys.imageio.spi.ImageReaderSpiBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
````

----------- java code------------

````java
public class Image {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		RenderedImage  image1;
		RenderedImage  image2;
		ArrayList<RenderedImage> images = new ArrayList<RenderedImage>();
		try {
			//BufferedImage image = ImageIO.read(new File("D:\\4-mas_wps\\1-WPS\\2-Implementation\\project\\1-Registration\\DisplayTif\\1.jpg"));	
			File img1 = new File("D:\\5-DATA\\aks.tif");
			File img2 = new File("D:\\5-DATA\\UAV\\50m\\IMG_0485_2.tif");
			image1 = ImageIO.read(img1);
			image2 = ImageIO.read(img2);
			images.add(0, image1);
			images.add(1, image2);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.out.println(images);

	}
}
````

**Comment by haraldk** [comment]
Hi,

Seems you are simply missing the imageio-core.jar from your classpath. Note that you will need it and the imageio-metadata.jar on classpath for the TIFF plugin to work. 


— 
Harald K

Sendt fra min iPhone

**Comment by haraldk** [comment]
Did the above solve you problem?

-- 
Harald K

**Comment by soshianet** [comment]
I added some jar file such as imageio-core, imageio-iff, imageio-tiff, imageio-metadata and twelvemonkeys-twelvemonkeys-3.4-SNAPSHOT-tests on classpath, but happend error....

Exception in thread "main" java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at imageio.ReadTif.main(ReadTif.java:32)
Caused by: java.lang.NoClassDefFoundError: com/twelvemonkeys/lang/Validate
	at com.twelvemonkeys.imageio.spi.ReaderWriterProviderInfo.<init>(ReaderWriterProviderInfo.java:90)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFProviderInfo.<init>(TIFFProviderInfo.java:42)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi.<init>(TIFFImageReaderSpi.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.twelvemonkeys.lang.Validate
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

**Comment by haraldk** [comment]
Hi again,

You are still missing some dependencies, it seems. 

Not sure why you added the `*-tests.jar`, you don't need that. However, you need the `common-*.jar`s. It's all described in the readme, here: [Manual Dependency Example](https://github.com/haraldk/TwelveMonkeys#manual-dependency-example)

-- 
Harald K

**Comment by soshianet** [comment]
Hiii,
it works fine, thanks so much...
