### ISSUE TITLE
IOException while reading a particular PSB file

### ISSUE THREAD

**Issue by vsarya** [haraldk/TwelveMonkeys#383]
Following error is observed while reading the attached "file.psb"

Google Drive Link of file.psb - https://drive.google.com/file/d/0B1SBo6BEhvipZFNxeUFlRnNnUmM/view?usp=sharing

````
javax.imageio.IIOException: Unsupported channel count/bit depth for CMYK PSD: 8 channels/8 bits
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getRawImageTypeForCompositeLayer(PSDImageReader.java:246)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getRawImageTypeInternal(PSDImageReader.java:143)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getImageTypes(PSDImageReader.java:264)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:372)
	at com.day.cq.dam.handler.standard.psd.PsdHandler.getImage(PsdHandler.java:137)
	at com.day.cq.dam.core.impl.cache.CQBufferedImageCache.getImage(CQBufferedImageCache.java:123)
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createImageLayer(CommonsGfxRenderer.java:490)
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createLayer(CommonsGfxRenderer.java:165)
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.render(CommonsGfxRenderer.java:116)
	at com.adobe.cq.gfx.impl.GfxImpl.render(GfxImpl.java:94)
	at com.day.cq.dam.core.impl.RenditionMakerImpl$PlanBasedTemplate.apply(RenditionMakerImpl.java:131)
	at com.day.cq.dam.core.impl.RenditionMakerImpl.generateRenditions(RenditionMakerImpl.java:210)
	at com.day.cq.dam.core.process.CreateThumbnailProcess.createThumbnails(CreateThumbnailProcess.java:120)
	at com.day.cq.dam.core.process.ThumbnailProcess.execute(ThumbnailProcess.java:102)
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:93)
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:194)
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:258)
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:502)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:293)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:60)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by haraldk** [comment]
Hi Vishal,

There's currently a limitation in the `PSDImageReader` that CMYK PSD (and PSB) files can only have 4 (CMYK) or 5 (CMYK + Alpha) channels. Your file has 8 channels (that is probably 4 different alpha channels, or masks).

I see that this is handled differently for RGB, in that only the first alpha channel is read, and the rest ignored. Implementing it the same way for CMYK should be quite easy. I'll try to include it in the next release.


Best regards,

-- 
Harald K

**Comment by vsarya** [comment]
Thanks @haraldk for such early response. 
Can you give an idea when will the next release be around ?

**Comment by haraldk** [comment]
It will be out as soon as possible. :-)

Unfortunately, I can't be more specific than that. But I will try to push a fix in the mean time, so that you can build a new version with extra channel support in the mean time.

Best regards,

-- 
Harald K

**Comment by vsarya** [comment]
@haraldk Okay Thanks.

**Comment by haraldk** [comment]
Fixed in latest master.

-- 
Harald K

**Comment by vsarya** [comment]
@haraldk Similar error is observed for RGB psd too. Can you fix that also ?

**Comment by vsarya** [comment]
@haraldk Although the IOException doesn't come now but the renditions generated are blank for the attached file. Can you please have a look ?

**Comment by haraldk** [comment]
The attached file doesn't seem to have a real "preview" or "composite layer" included (it's all white). The file also shows up all white in the MacOS Preview application. This is consistent with the metadata, `hasRealMergedData` which is false. 

I don't own Photoshop myself, but I think this is an option you can select when you save/export a PSD/PSB. 

If you read the individual layers though, the different elements and shadows are all there. So, it  seems good to me. 

-- 
Harald K
