### ISSUE TITLE
IOException while reading a particular PSD file

### ISSUE THREAD

**Issue by vsarya** [haraldk/TwelveMonkeys#403]
Following error is observed while reading the attached "Fruit(CMYK16).psd"

Google Drive Link of Fruit(CMYK16).psd -
https://drive.google.com/open?id=1dAr7QnFqtNUU6a34vScfo6XA8cKFfQ6M

````
05.01.2018 16:18:09.555 *WARN* [JobHandler: /var/workflow/instances/server0/2018-01-04_1/update_asset_232:/content/dam/Fruit(CMYK16).psd/jcr:content/renditions/original] com.day.cq.dam.handler.standard.psd.PsdHandler getImage: error while getting image for PSD [/content/dam/Fruit(CMYK16).psd/jcr:content/renditions/original]: 
javax.imageio.IIOException: Wrong image resource type, expected '8BIM': 'MeSa'
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageResource.read(PSDImageResource.java:167) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readImageResources(PSDImageReader.java:904) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getEmbeddedColorSpace(PSDImageReader.java:343) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getRawImageTypeForCompositeLayer(PSDImageReader.java:222) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getRawImageTypeInternal(PSDImageReader.java:143) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getImageTypes(PSDImageReader.java:264) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:372) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.day.cq.dam.handler.standard.psd.PsdHandler.getImage(PsdHandler.java:137) [com.day.cq.dam.cq-dam-handler:5.11.18]
	at com.day.cq.dam.core.impl.cache.CQBufferedImageCache.getImage(CQBufferedImageCache.java:123) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createImageLayer(CommonsGfxRenderer.java:490) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createLayer(CommonsGfxRenderer.java:165) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.render(CommonsGfxRenderer.java:116) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.adobe.cq.gfx.impl.GfxImpl.render(GfxImpl.java:94) [com.adobe.cq.cq-gfx:1.4.2]
	at com.day.cq.dam.core.impl.RenditionMakerImpl$PlanBasedTemplate.apply(RenditionMakerImpl.java:131) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.day.cq.dam.core.impl.RenditionMakerImpl.generateRenditions(RenditionMakerImpl.java:210) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.day.cq.dam.core.process.CreateWebEnabledImageProcess.createWebEnabledImage(CreateWebEnabledImageProcess.java:164) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.day.cq.dam.core.process.ThumbnailProcess.execute(ThumbnailProcess.java:106) [com.day.cq.dam.cq-dam-core:5.11.228]
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:93) [com.day.cq.workflow.cq-workflow-impl:6.2.6]
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:194) [com.adobe.granite.workflow.core:2.0.146]
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:258) [com.adobe.granite.workflow.core:2.0.146]
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:502) [org.apache.sling.event:4.2.10]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:293) [org.apache.sling.event:4.2.10]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:60) [org.apache.sling.event:4.2.10]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:229) [org.apache.sling.event:4.2.10]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

````

**Comment by haraldk** [comment]
Hi Vishal,

This file contains 3 "resources" that have the "magic" sginature "MeSa", instead of the expected "8BIM" for a Photoshop resource. Normal "8BIM" resources can be found both before and after these alien resources. The "MeSa" resources otherwise conforms to a Photoshop resource, so the file can be read if I disable the check for "8BIM".

However, according to the format documentation (http://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_pgfId-1037504), no other signatures than "8BIM" is allowed. So this file is really corrupted. 

I'm reluctant to add support for such corrupted/malformed files.

Do you know what software that wrote it (I can see the file claims Adobe Photoshop CS Macintosh, but I'm not really convinced)? 

Do you have many such files?

Can Adobe Photoshop read it? How about other software like the Gimp etc?


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
With a little Google-fu, I found http://fileformats.archiveteam.org/wiki/Photoshop_Image_Resources, which claims that the "MeSa" resources are associated with Adobe ImageReady:

> Each block usually begins with the ASCII characters "8BIM", a signature that appears in several Photoshop formats. Other block signatures that have been observed are "MeSa" (apparently associated with ImageReady), "PHUT" (apparently associated with PhotoDeluxe), "AgHg", and "DCSR".

Hmmm...

Maybe we could add support for that set of resource identifiers.

-- 
Harald K

**Comment by haraldk** [comment]
Added support for MeSa and other extra known resource signatures.
