### ISSUE TITLE
javax.imageio.IIOException: No SOF segment in stream in ImageIO.read operation 

### ISSUE THREAD

**Issue by jijokrishnan33** [haraldk/TwelveMonkeys#407]
I am getting javax.imageio.IIOException: No SOF segment in stream exception while executing the following code.

byte[] imageByte = Base64.decodeBase64(base64String);
            bis = new ByteArrayInputStream(imageByte);
            image = ImageIO.read(bis);

This issue occurs for some random images. 

Please find below the stack trace

javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:762)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:334)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFJPEGDecompressor.decodeRaw(TIFFJPEGDecompressor.java:226)
	at com.github.jaiimageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2583)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1144)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1414)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)

**Comment by haraldk** [comment]
Hi @jijokrishnan33 

I see from the stack trace that you are trying to read a TIFF image, using the JAI TIFFImageReader. You should probably report the bug to the JAI developers, rather than here. 

But if you attach an image that causes the problem, I can take a look, and see if there's something special about it, that could cause this exception. Also, please state the version of the library you are using, and the Java version and operating system.


Best regards,

-- 
Harald K

**Comment by jijokrishnan33** [comment]
Hi Harald,

Thanks for the quick replay.

I can't share the image due to some security reason. I am using 3.3.2 version of imageio-jpeg jar.java version is 1.8.

It would be helpful if you could give some general  information on why "No SOF segment in stream" error is thrown normally.

**Comment by haraldk** [comment]
I'm sorry, but I won't be able to help you much without the image in question. 

The "No SOF segment in stream" is generally an indication of... that the JPEGImageReader can't find a SOF  (JPEG Start Of Frame) segment in the stream. Without a SOF, there can't be any JPEG image data, so further decoding is meaningless.

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Please see the updated response above.
