### ISSUE TITLE
Writing a TIF image with specific compression and resolution

### ISSUE THREAD

**Issue by cypher0six** [haraldk/TwelveMonkeys#439]
I have an application that is trying to write a TIF image with Group 4 compression enabled, and with 200 dpi. Here is the method in question that is failing:

```
    private static void repairImageFile(String fileName)
            throws IOException {

        // define an input stream to the file


        final File file = new File(fileName);
        final ImageInputStream imageInputStream = ImageIO.createImageInputStream(file);

        if (imageInputStream == null) {
            throw new IOException("Unable to obtain an input stream for file: " + fileName);
        }


        // get list of readers capable of reading the loaded file


        final Iterator<ImageReader> imageReaders = ImageIO.getImageReaders(imageInputStream);

        if (imageReaders == null) {
            throw new IOException("Unable to obtain an image reader to decode the file: " + fileName);
        }


        // select the first available reader and use it to extract an image from a potential list of
        // images. we do this because some images we have received have empty second pages, and
        // the call to count those pages fails on these images. so we are left with converting all
        // images we receive in the manner in which we decide.


        final ImageReader imageReader = imageReaders.next();
        imageReader.setInput(imageInputStream, false, true);

        final BufferedImage image = imageReader.read(0); // get first image from file


        // define an output stream to the file


        final ImageOutputStream imageOutputStream = ImageIO.createImageOutputStream(file);

        if (imageOutputStream == null) {
            throw new IOException("Unable to obtain an output stream for file: " + fileName);
        }


        // set the byte order to little endian
        // our various imaging systems downstream will not be able to support the
        // big endian (motorola) byte order


        imageOutputStream.setByteOrder(ByteOrder.LITTLE_ENDIAN);


        // get a list of writers capable of writing the tif format


        final Iterator<ImageWriter> imageWriters = ImageIO.getImageWritersByFormatName("tif");

        if (imageWriters == null) {
            throw new IOException("Unable to obtain an image writer for the tif file format!");
        }


        // select the first writer available


        final ImageWriter imageWriter = imageWriters.next();
        imageWriter.setOutput(imageOutputStream);


        // define compression parameters


        final ImageWriteParam parameters = imageWriter.getDefaultWriteParam();
        parameters.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
        parameters.setCompressionType("CCITT T.6"); // Group 4 Compression
        parameters.setCompressionQuality(0.2f);


        // set the resolution of the target image to 200 dpi


        final List<Entry> entries = new ArrayList<Entry>();
        entries.add(new TIFFEntry(TIFF.TAG_X_RESOLUTION, new Rational(200)));
        entries.add(new TIFFEntry(TIFF.TAG_Y_RESOLUTION, new Rational(200)));

        final IIOMetadata tiffImageMetadata = new TIFFImageMetadata(entries);


        // write the image to a file


        try {
            imageWriter.write(tiffImageMetadata, new IIOImage(image, null, null), parameters);
        } catch (IOException e) {
            throw new IOException("Unable to write image to file: " + fileName, e);
        }


        // close streams, release resources


        imageInputStream.close();
        imageOutputStream.close();
    }
```

This fails with the following stack trace:

```
java.lang.IllegalArgumentException: Bad format name: "com_sun_media_imageio_plugins_tiff_stream_1.0". Expected one of [com_sun_media_imageio_plugins_tiff_image_1.0, javax_imageio_1.0]
	at com.twelvemonkeys.imageio.AbstractMetadata.validateFormatName(AbstractMetadata.java:132)
	at com.twelvemonkeys.imageio.AbstractMetadata.getAsTree(AbstractMetadata.java:71)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFStreamMetadata.configureStreamByteOrder(TIFFStreamMetadata.java:142)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.prepareWriteSequence(TIFFImageWriter.java:931)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.write(TIFFImageWriter.java:137)
	at org.x.imaging.ImageProcessor.repairImageFile(ImageProcessor.java:229)
	at org.x.imaging.ImageProcessor.handleRepairCommand(ImageProcessor.java:125)
	at org.x.imaging.ImageProcessor.main(ImageProcessor.java:57)
```

Is this a bug or am I doing something wrong? Is there a way to set this format name explicitly? 

This method "works" if I replace `tifImageMetadata` with a null reference. However, the image is written at 72 dpi instead of 200 dpi. It's only when trying to use the TIFFImageMetadata class directly instead of `imageWriter.getDefaultStreamMetadata()` that this particular exception is thrown.

**Comment by cypher0six** [comment]
Hi,

You are quite correct! The mistake was mine all along. :) Making that small change has corrected the issue. Thank you for your help, and thanks for this library!
