### ISSUE TITLE
PSD Plugin doesn't exist inside of JAR

### ISSUE THREAD

**Issue by POE-Addon-Launcher** [haraldk/TwelveMonkeys#463]
Trying to use ImageIO.read() to read a PSD file, it works fine in my IDE, but when I try to do it inside of a packaged jar it doesn't work after some debugging I found out that when I use the code:

ImageIO.scanForPlugins()
            IIORegistry.getDefaultInstance().registerApplicationClasspathSpis()
            val ir = ImageIO.getImageReadersByFormatName("PSD")
            while (ir.hasNext())
            {
                val r = ir.next() as ImageReader
                println(r)
            }

When running from IDE this will print:

    com.twelvemonkeys.imageio.plugins.psd.PSDImageReader@41975e01

However, when running in a jar it will not print anything, I've read about using 

<web-app ...>

...

    <listener>
        <display-name>ImageIO service provider loader/unloader</display-name>
        <listener-class>com.twelvemonkeys.servlet.image.IIOProviderContextListener</listener-class>
    </listener>

...

</web-app>

But I don't have a webapp I have a maven project!

**Comment by POE-Addon-Launcher** [comment]
I was able to get a stacktrace:

`java.lang.IllegalStateException: img must not be null
        at MenuController.showPSDPreview(Controller.kt:213)
        at MenuController.handleDragDrop(Controller.kt:171)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
        at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:2933)
        at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3159)
        at javafx.scene.Scene$DnDGesture.access$6400(Scene.java:2909)
        at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2873)
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$308(GlassSceneDnDEventHandler.java:95)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$362(GlassViewEventHandler.java:745)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:744)
        at com.sun.glass.ui.View.handleDragDrop(View.java:712)
        at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
kotlin.Unit`

**Comment by haraldk** [comment]
Hi,

It's a little hard to try to diagnose the problem given the limited information, but I'm guessing that you are somehow re-packaging the plugins in a "fat" JAR or something similar? Can you expand on how your package your application? What JARs do you have on class path when you run outside IDE?

As you say, it works in the IDE, we know the problem is not the plugin itself, but that `ImageIO` isn't picking it up. A typical problem when creating a "fat" JAR, is that by just copying all the files from all the JARs into the destination folder/JAR, you'll end up overwriting the entries in `META-INF/services/`, required for proper SPI registration (the symptoms are consistent with this). Depending on what plugin you use for this, you might need to choose a different "merge" strategy.

PS: `ImageIO.scanForPlugins()` internally is just `theRegistry.registerApplicationClasspathSpis();` (where `theRegistry` is just `IIORegistry.getDefaultInstance()`), so invoking both will end up doing the same thing twice.

-- 
Harald K

**Comment by POE-Addon-Launcher** [comment]
I'm using maven and I'm using the maven command: "clean compile assembly:single"

And these are the dependencies I use:

`   
<dependency>

        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-bmp</artifactId>
        <version>3.4</version>
    </dependency>
    <dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-psd</artifactId>
        <version>3.4</version>
    </dependency>
    <dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-core</artifactId>
        <version>3.4</version>
    </dependency>
    <dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-metadata</artifactId>
        <version>3.4</version>
    </dependency>`

Is this the information you needed?

**Comment by POE-Addon-Launcher** [comment]
I was able to fix it by removing the dependency of  Imageio-bmp

**Comment by haraldk** [comment]
Okay,

Thanks!  I'm pretty sure then, that the problem is what I described above. It goes away by removing the BMP plugin, because you are left with only a single `META-INF/services` entry (the `imageio-core` and `imageio-metadata` does not contain such entries). 

As I said, you need some way to merge the entries. I don't use the Maven Assembly plugin myself, but I belive the solution is described [here](http://maven.apache.org/plugins/maven-assembly-plugin/examples/single/using-container-descriptor-handlers.html), see the "metaInf-services" section.


Best regards,

-- 
Harald K
