### ISSUE TITLE
EOFException for a particular PSD file.

### ISSUE THREAD

**Issue by Himanich** [haraldk/TwelveMonkeys#468]
Hi Harald,

Following error is observed while reading "Non-Working_Tony_Tiger_Standing.psd"
The file could be found at:
https://drive.google.com/open?id=1vogNsVLdpK7z4rP-mlaL-8RwPUsros8d

`java.io.EOFException: null
	at javax.imageio.stream.ImageInputStreamImpl.readInt(Unknown Source)
	at javax.imageio.stream.ImageInputStreamImpl.readUnsignedInt(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readLayerAndMaskInfo(PSDImageReader.java:972)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getNumImages(PSDImageReader.java:1157)
	at com.twelvemonkeys.imageio.ImageReaderBase.checkBounds(ImageReaderBase.java:189)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:359)`

**Comment by haraldk** [comment]
After some more investigation, the file seems to be truncated. According to the format, the layers and mask  info section of the file should start at `581494` and be `41210728` bytes long. However, the file is only `39131572` bytes in total... As a result we'll get the `EOFException` you see above.

If we ignore the exception, we can read the first 28 or so layers, while the 29th seems to be chopped of in the middle, including all later layers and the composite (merged) layer. 

I don't think there's anything wrong with the reader here. :-)

Best regards,

-- 
Harald K
