### ISSUE TITLE
Out of memory while reading Exif data from JPEG file

### ISSUE THREAD

**Issue by skirjak** [haraldk/TwelveMonkeys#469]
While trying to read exif data from the attached image we got an "out of memory" exception.
Looks like the image is somehow corrupted but maybe the exception thrown can be prevented as it tears down the our whole application. Please take a look. Thanks in advance!

````
Uncaught error from thread [application-thumbnailing-context-26] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.OutOfMemoryError: Java heap space
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readValue(TIFFReader.java:407)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readValueAt(TIFFReader.java:324)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readEntry(TIFFReader.java:298)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:146)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readSubIFDs(TIFFReader.java:188)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:158)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readSubIFDs(TIFFReader.java:188)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:158)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readSubIFDs(TIFFReader.java:188)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:158)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readSubIFDs(TIFFReader.java:188)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:158)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readLinkedIFDs(TIFFReader.java:120)
    at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.read(TIFFReader.java:109)
    at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.read(EXIFReader.java:55)
````

![20190117_die macht der gefuhle_ute frevert](https://user-images.githubusercontent.com/9862530/51521613-60512800-1e27-11e9-8afe-0a8c08a9a054.jpg)

**Comment by haraldk** [comment]
Hi skirjak,

The Exif data of the file seems to be corrupted. It contains Exif within Exif within Exif within Exif... And the inner one does contain a bad tag/offset/count (count is `808596017`, supposedly LONG/32 bit values). 

I could probably skip parsing of the nested Exif IFDs, but that means you'll lose some information.

-- 
Harald K

**Comment by skirjak** [comment]
Hi, I ran into the same issue with the following image:
![goslar diskurs](https://user-images.githubusercontent.com/9862530/51971165-d46b7b80-2478-11e9-90de-efc010126eed.jpg)


I suggest to drop the exif data in such cases.

**Comment by haraldk** [comment]
The fix I made for the first image works for this one as well. I just need to clean the code and create a test case before committing.

-- 
Harald K

**Comment by haraldk** [comment]
Sorry for taking too long. My initial fix works reliably only for the first image. 

The problem with the second one is different, here the TIFF contains bad offsets, but I have a fix for this issue soon as well.

-- 
Harald K

**Comment by haraldk** [comment]
Fixed.
