### ISSUE TITLE
java.awt.color.CMMException: Can not access specified profile

### ISSUE THREAD

**Issue by waqqasdadabhoy** [haraldk/TwelveMonkeys#474]
I'm trying to use TwelveMonkeys to get the dimensions of https://ia601303.us.archive.org/16/items/mbid-22fe8b56-a3b4-4ba3-acb8-2b14eba06dd3/mbid-22fe8b56-a3b4-4ba3-acb8-2b14eba06dd3-11661564753.jpg but I'm getting the following error:

```java
java.awt.color.CMMException: Can not access specified profile.
  at sun.java2d.cmm.lcms.LCMS.getProfileSizeNative(Native Method)
  at sun.java2d.cmm.lcms.LCMS.getProfileSize(LCMS.java:68)
  at java.awt.color.ICC_Profile.getData(ICC_Profile.java:1330)
  at com.twelvemonkeys.imageio.color.ColorSpaces.getProfileHeaderWithProfileId(ColorSpaces.java:147)
  at com.twelvemonkeys.imageio.color.ColorSpaces.isCS_sRGB(ColorSpaces.java:239)
  at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:374)
  at javax.imageio.ImageIO.read(ImageIO.java:1448)
  at javax.imageio.ImageIO.read(ImageIO.java:1400)
```

If I try vanilla Java (without TwelveMonkeys), I get the same error, but with a different stacktrace:
```java
java.awt.color.CMMException: Can not access specified profile.
  at sun.java2d.cmm.lcms.LCMS.getProfileSizeNative(Native Method)
  at sun.java2d.cmm.lcms.LCMS.getProfileSize(LCMS.java:68)
  at java.awt.color.ICC_Profile.getData(ICC_Profile.java:1330)
  at com.sun.imageio.plugins.jpeg.JPEGImageReader.setImageData(JPEGImageReader.java:687)
  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:620)
  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:614)
  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1070)
  at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1050)
  at javax.imageio.ImageIO.read(ImageIO.java:1448)
  at javax.imageio.ImageIO.read(ImageIO.java:1400)
```

This is the code I'm using to read the image (in a Scala REPL):
```scala
import javax.imageio.ImageIO
import java.net.URL
ImageIO.read(new URL("https://ia601303.us.archive.org/16/items/mbid-22fe8b56-a3b4-4ba3-acb8-2b14eba06dd3/mbid-22fe8b56-a3b4-4ba3-acb8-2b14eba06dd3-11661564753.jpg"))
```

I'm using OpenJDK 1.8.0_191 on Ubuntu 18.10.

**Comment by waqqasdadabhoy** [comment]
I did some testing of my own, and found that wrapping the `else if` condition in a try-catch allows it to continue, and I am getting the correct width & height from the returned `BufferedImage`.

I've committed the change at https://github.com/waqqasdadabhoy/TwelveMonkeys/commit/26ab57f8987691d163794ed7478ad491cd7fb606 , and put in the `ex.printStackTrace()` to verify which exception was being caught.

However, I'm not sure if this is the right way to go about it, or if the error handling should be in `ColorSpaces.isCS_sRGB` or `ColorSpaces.getProfileHeaderWithProfileId`.

**Comment by haraldk** [comment]
I think the exception should be handled in the ColorSpaces class, as close to the source of the exception as possible. But I need to look into it a bit more to figure out where the best location is. 

.k

**Comment by waqqasdadabhoy** [comment]
I've updated my change to handle it close to the source of the exception: https://github.com/waqqasdadabhoy/TwelveMonkeys/commit/57f230d80ec53c7a21b98bb41aa660642db39d07

I've changed it to return `null` in case of an exception, but I'm not sure if it should be returning `null` or some other value. I see that other methods in the class (e.g. `readProfileFromClasspathResource`) do return `null`.

**Comment by haraldk** [comment]
I don't think returning `null` there is appropriate, as it may just lead to `NullPonterException`s later. Instead, I figured we can solve this issue by doing some more validation in the `ColorSpaces.validateColorSpace` method.

I've changed it so it now reads:

```java
    private static void validateColorSpace(final ICC_ColorSpace cs) {
        // Validate the color space, to avoid caching bad profiles/color spaces
        // Will throw IllegalArgumentException or CMMException if the profile is bad
        cs.fromRGB(new float[] {0.999f, 0.5f, 0.001f});

        // This breaks *some times* after validation of bad profiles,
        // we'll let it blow up early in this case
        cs.getProfile().getData();
    }
```

This will prevent the broken ICC profile to be used in the first place, and trigger the correct warnings in the `JPEGImageReader` (warning about the corrupted ICC profile, and that it will be ignored). 


-- 
Harald K

**Comment by haraldk** [comment]
Fixed.
