### ISSUE TITLE
Cannot Read the thumb.db File of Windows 10

### ISSUE THREAD

**Issue by AKMANSoft** [haraldk/TwelveMonkeys#541]
I have been trying to get the BufferedImages from thumbcache_32.db using the thumbdb plugin but its giving me 

```
Exception in thread "main" com.twelvemonkeys.io.ole2.CorruptDocumentException: Not an OLE 2 Compound Document
	at com.twelvemonkeys.io.ole2.CompoundDocument.readHeader(CompoundDocument.java:257)
	at com.twelvemonkeys.io.ole2.CompoundDocument.<init>(CompoundDocument.java:160)
	at imageio.thumbsdb@3.5/com.twelvemonkeys.imageio.plugins.thumbsdb.ThumbsDBImageReader.init(ThumbsDBImageReader.java:270)
	at imageio.thumbsdb@3.5/com.twelvemonkeys.imageio.plugins.thumbsdb.ThumbsDBImageReader.getNumImages(ThumbsDBImageReader.java:305)
	at triage/com.hashscan.controls.ThumbReader.read(ThumbReader.java:36)
	at triage/com.hashscan.controls.ThumbReader.main(ThumbReader.java:53)
```

Below is my Code. 

```java
package com.hashscan.controls;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStream;

import com.twelvemonkeys.imageio.plugins.thumbsdb.ThumbsDBImageReader;

public class ThumbReader {

	private String path;
	private ImageInputStream input;
	private ThumbsDBImageReader reader;
	
	public ThumbReader(String path) {
		this.path = path;
		reader = new ThumbsDBImageReader();
	}
	
	public void read() throws IOException {
		
		
		File file = new File(path);
		
		if(!file.exists())
			new IOException("File not Exists");
			
		
		input = ImageIO.createImageInputStream(new File(path));
		reader.setInput(input);
		
		//if(reader.isPresent(path)){
			for (int i = 0; i < reader.getNumImages(true); i++) {
			    BufferedImage thumb = reader.read(i, null);
			    System.err.println(thumb.getWidth());
			    // do something with it...
			}

			reader.dispose(); // These last two, preferably in a finally block or "try-with-resource"
			input.close();
		//}

	}
	
	public static void main(String[] args) throws IOException {
		System.err.println("Start Reader");
		
		String path = "E:\\dbs\\thumbcache_2560.db";
		ThumbReader reader = new ThumbReader(path);
		reader.read();
		
		System.err.println("End Reader");
	}	
}
```

Im using 3.5 version. In my pomI have these dependencies. 

```xml
<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.common/common-lang -->
		<dependency>
			<groupId>com.twelvemonkeys.common</groupId>
			<artifactId>common-lang</artifactId>
			<version>${tweleve.version}</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.common/common-io -->
		<dependency>
			<groupId>com.twelvemonkeys.common</groupId>
			<artifactId>common-io</artifactId>
			<version>${tweleve.version}</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.common/common-image -->
		<dependency>
			<groupId>com.twelvemonkeys.common</groupId>
			<artifactId>common-image</artifactId>
			<version>${tweleve.version}</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-core -->
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-core</artifactId>
			<version>${tweleve.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-metadata -->
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-metadata</artifactId>
			<version>${tweleve.version}</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-thumbsdb -->
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-thumbsdb</artifactId>
			<version>${tweleve.version}</version>
		</dependency>
```

**Comment by haraldk** [comment]
Hi @AKMANSoft ,

I'll look into it, but to be able to trouble-shoot this further, I need a copy of your `thumbcache_32.db` file.

-- 
Harald K

**Comment by AKMANSoft** [comment]
Thanks you for looking into the issue. below is the link to get the cache files. 

[](https://www.dropbox.com/s/ef1kubctasauhtg/Thumbnail.zip?dl=0)

**Comment by haraldk** [comment]
Hi again,

Unfortunately, your files are in the new Windows Vista/7/10 format. These are not OLE2 Compound Documents, and a completely different format not supported by the ThumbsDBImageReader. 

It doesn't look like a super difficult format to parse, but I don't have any plans to add support for it at the moment. 


Best regards,

--
Harald K
