### ISSUE TITLE
javax.imageio.IIOException: No SOF segment in stream

### ISSUE THREAD

**Issue by Queatz** [haraldk/TwelveMonkeys#542]
I have an image that is crashing my app with this error.

```
javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:884)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getWidth(JPEGImageReader.java:209)
```

This is the image
https://drive.google.com/file/d/1afUFucDXUy-J9_UBqZz09R0jeA-aT-lf/view?usp=sharing

Here's what I'm doing:

Saving the image:
```java
        ImageReader reader;
        IIOImage imageWithExif;
        BufferedImage image;

        try {
            reader = this.image(getFileFromName(metadata.file));
            image = reader.read(0);
            image = this.scale(image, size.x, size.y > 0 ? size.y : (int) (size.x / getAspectRatio(metadata)));
            imageWithExif = reader.readAll(0, null);
            imageWithExif.setMetadata(reader.getImageMetadata(0));
            imageWithExif.setRenderedImage(image);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }

        FileImageOutputStream outputStream = openOutputStream(metadata.path, metadata.name, size);

        try {
            ImageWriter writer = ImageIO.getImageWriters(ImageTypeSpecifier.createFromBufferedImageType(image.getType()), reader.getFormatName()).next();
            writer.setOutput(outputStream);
            writer.write(imageWithExif);
            outputStream.close();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
```

Reading the saved image:
```java
        ImageInputStream iis = ImageIO.createImageInputStream(file);
        ImageReader reader = ImageIO.getImageReaders(iis).next();
        reader.setInput(iis);
        reader.getWidth(0); // crash happens here
```

**Comment by Queatz** [comment]
Fixed was replacing these lines:

```java
imageWithExif = reader.readAll(0, null);
imageWithExif.setMetadata(reader.getImageMetadata(0));
imageWithExif.setRenderedImage(image);
```

with this line
```java
imageWithExif = new IIOImage(image, null, reader.getImageMetadata(0));
```

**Comment by haraldk** [comment]
Hi,

Just a clarification. You should use:

    imageWithExif = reader.readAll(0, null);

*or*

    imageWithExif = new IIOImage(image, null, reader.getImageMetadata(0));

as `readAll` does as it says, it reads "all" (that is, both image and metadata), so your first example does everything twice. Setting the metadata or image directly from the reader should in theory just replace the values with a new set of identical values, so I'm not really sure why you don't get a good image from that though...

-- 
Harald K
