### ISSUE TITLE
java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/plugins/jpeg/JPEGImageReader$3 in webapplication

### ISSUE THREAD

**Issue by egloffmark** [haraldk/TwelveMonkeys#544]
Hello. We face currently the issue on our Linux Ubuntu server with a tomcat 9 that the plugins not get found or loaded although we have the listener initialized. The weird thing the issue is not happening when we test it locally on windows or on a linux desktop machine.

Environment
- Java OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
- Tomat 9.0.31
- Server OS: Ubuntu 18.04.4 LTS
- twelvemonkeys version 3.5

Any hints what we can try? any verbose loggng we can turn on or any additonal java statement we can add to test what could be wrong or missing?

**StackTrace**
```
Caused by: java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/plugins/jpeg/JPEGImageReader$3
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getRawImageType(JPEGImageReader.java:311)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:382)
        at javax.imageio.ImageIO.read(ImageIO.java:1462)
        at javax.imageio.ImageIO.read(ImageIO.java:1357)
        at com.ontius.core.web.file.service.FileServiceImpl.readImage(FileServiceImpl.java:228)
        at com.ontius.core.web.file.service.FileServiceImpl.saveImage(FileServiceImpl.java:201)
        at com.ontius.vrmandat.web.file.service.MediaService.copyAndModifyImage(MediaService.java:312)
        at com.ontius.vrmandat.web.file.service.MediaService.saveSquaredImage(MediaService.java:232)
        at com.ontius.vrmandat.web.file.service.MediaService.saveImageWithThumbnails(MediaService.java:66)
        at com.ontius.vrmandat.rest.controller.UserController.saveProfileImage(UserController.java:225)
        at com.ontius.vrmandat.rest.controller.UserController$$FastClassBySpringCGLIB$$914a0c05.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at com.ontius.vrmandat.rest.controller.UserController$$EnhancerBySpringCGLIB$$2201e617.saveProfileImage(<generated>)
        at sun.reflect.GeneratedMethodAccessor9180.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:215)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:142)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        ... 64 common frames omitted
```
Spring Servlet Initialization:
```
import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;

public class ApplicationInitializer extends AbstractAnnotationConfigDispatcherServletInitializer  {
    ...
    @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        super.onStartup(servletContext);
        servletContext.addListener(IIOProviderContextListener.class);
    }
}
```
Maven POM.xml
```
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-core</artifactId>
            <version>3.5</version>
        </dependency>
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-jpeg</artifactId>
            <version>3.5</version>
        </dependency>
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-tiff</artifactId>
            <version>3.5</version>
        </dependency>
        <dependency>
            <groupId>com.twelvemonkeys.servlet</groupId>
            <artifactId>servlet</artifactId>
            <version>3.5</version>
        </dependency>
```

**Comment by haraldk** [comment]
Hi,

This seems like a very odd issue... The line in the stack trace ([JPEGImageReader:311](https://github.com/haraldk/TwelveMonkeys/blob/4922ccf80bc944e3135d76ed1d5fbf7b6747b573/imageio/imageio-jpeg/src/main/java/com/twelvemonkeys/imageio/plugins/jpeg/JPEGImageReader.java#L311)) is a switch statement, but your exception indicates class loading happens there: 

````java
        switch (csType) {
````

It is however a switch on an enum instance, it might be that the compiler generates inner classes for this, I'm not that into the specifics of the generated code... In any way, it seems like you are seeing a class loader issue, as you have trouble loading an anonymous inner class of an already initialised class. 

Perhaps something is accessing ImageIO before the context listener is installed? Or that there are stale instances from elsewhere (ie. other apps in same server)? These kinds of issues is unfortunately hard to debug even when you have all the components directly available, remote guessing is almost impossible. So I'm afraid I can't help you much here, unless you can create a reproducible test case for me... 

I'm not sure if Tomcat still allows for installing common/shared libraries outside the (web) applications, but if it does, that might be a possible fix. Ie. install all TwelveMonkeys JARs in common or shared libs, and change your dependencies to "provided" scope. 

PS: Looking at your POM excerpt, you have an explicit dependency for `twelvemonkeys-imageio-core`, but none for `twelvemonkeys-common-lang`, `twelvemonkeys-common-io`, `twelvemonkeys-common-image` or `twelvemonkeys-imageio-metadata`. Probably not the problem though, as these should be handled automatically as transitive dependencies...

-- 
Harald K

**Comment by egloffmark** [comment]
Thank you, I found in the meantime a workaround to put the libraries into the "tomcat/lib" folder. 
I will try to reproduce the issue with a minimized application (i.e. with a docker) so I can handover it to you.

**Comment by haraldk** [comment]
Great,

That's a viable workaround I guess. Less than ideal, as you can't just update the dependencies, rebuild and redeploy, but better than not working at all.

I was right about enum switch, it is indeed implemented through an inner class with a static lookup-table. But the fact that this IS happening, does indicate that you have a `JPEGImageReader` in a "stale" state installed in the registry, but not able to look up its inner classes at runtime. I still think this is a class loading issue. Perhaps you have more applications running in this environment than locally?


-- 
Harald K

**Comment by haraldk** [comment]
Closing for now.

Feel free to reopen, if you find a way to reproduce in isolation.

-- 
Harald K
