### ISSUE TITLE
IllegalArgumentException when reading Adobe clipping path

### ISSUE THREAD

**Issue by aerpenbeck** [haraldk/TwelveMonkeys#550]
I'm reading Adobe clipping path information from JPEG and TIFF images and get an
```java.lang.IllegalArgumentException: Unexpected point```

```
at com.twelvemonkeys.lang.Validate.isTrue(Validate.java:197)
at com.twelvemonkeys.lang.Validate.isTrue(Validate.java:192)
at com.twelvemonkeys.imageio.path.AdobePathSegment.<init>(AdobePathSegment.java:100)
at com.twelvemonkeys.imageio.path.AdobePathSegment.<init>(AdobePathSegment.java:79)
at com.twelvemonkeys.imageio.path.AdobePathBuilder.nextSegment(AdobePathBuilder.java:237)
at com.twelvemonkeys.imageio.path.AdobePathBuilder.path(AdobePathBuilder.java:99)
at com.twelvemonkeys.imageio.path.Paths.buildPathFromPhotoshopResources(Paths.java:169)
at com.twelvemonkeys.imageio.path.Paths.readPath(Paths.java:128)
```

Here is an [example JPEG](https://drive.google.com/file/d/1B5WoWX5FfJm0pEdIR1K95nAUbMX1lZg0/view?usp=sharing) and here's an [example TIFF](https://drive.google.com/file/d/1X8NjZNBo8wnjnnmsfVWbonXBIeSuiGbu/view?usp=sharing).

These files have path points with cppy <= 0 or >= 1, e.g. [0,437500, -0,000965], [0,301760, 1,001002]

I'm mainly interested in the number of points and whether the path is closed or not.
Currently I don't see a way to ignore this kind of error and just continue with the next path segment.

Any advice would be greatly appreciated.

**Comment by haraldk** [comment]
Hi Arno,

Thanks for reporting!

I can reproduce your exception here using the given images. They do seem to be written by Adobe Photoshop, so they are probably correct... Re-reading the fine details in the format specification, it seems the range should actually be [-16...16], not the very limited [0...1]. 

It's probably easy to fix. Hope to have a fix ready soon.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Fixed, should be out in the new release.
