### ISSUE TITLE
Problem reading JPEG: "Bogus Marker Length" (Android Phone Camera)

### ISSUE THREAD

**Issue by Roman-it20one** [haraldk/TwelveMonkeys#553]
Hi,

trying to read the attached images fails with "bogus marker length" error. I was told they all were recorded with the camera of some android based mobile device. Happened with Java 8 + Twelvemonkeys 3.6

Best regards
Roman

```
Caused by: javax.imageio.IIOException: Bogus marker length
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:620)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:492)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:613)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getRawImageType(JPEGImageReader.java:770)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getRawImageType(JPEGImageReader.java:272)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:343)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
```

[images.zip](https://github.com/haraldk/TwelveMonkeys/files/4975066/images.zip)

**Comment by Roman-it20one** [comment]
Jpegsnoop actually shows an error parsing the jepg. Log attached.

"ERROR: Unknown IPTC TagMarker [0x00] @ 0x00000081. Skipping parsing."

[jpegsnoop_logfile.txt](https://github.com/haraldk/TwelveMonkeys/files/4988693/jpegsnoop_logfile.txt)

**Comment by haraldk** [comment]
Odd... 

They all seem to read and process fine for me (Java 8 + TwelveMonkeys 3.6). 

Do you have the exact code to reproduce the problem (ie. standalone main method or JUnit test case)?

I don't think the JPEGSnoop output is too important, it's just something inside the IPTC metadata, we don't really need that. 

PS: Your stack trace indicates you are not using the latest version (3.6), as the line numbers in JPEGImageReader do not match (ie. [JPEGImageReader line 343](https://github.com/haraldk/TwelveMonkeys/blob/ed14b971991951379365f975bd6d9caaea8a836b/imageio/imageio-jpeg/src/main/java/com/twelvemonkeys/imageio/plugins/jpeg/JPEGImageReader.java#L343) does not invoke `getRawImageType()`)... Can you please re-check that you are using the latest version?


Best regards,

-- 
Harald K

**Comment by Roman-it20one** [comment]
Thank you very much for your input. I was under the impression we updated to 3.6 properly but i'll re-check and give it another try. Will get back to you with more info later.

Best regards,
Roman

**Comment by Roman-it20one** [comment]
Turns out there was still an old imageio-jpeg jar file present that slipped under the radar when we updated. Now with 3.6 properly in place it does indeed run fine. Thanks for the help and sorry to waste your time!

Best regards,
Roman
