### ISSUE TITLE
javax.imageio.IIOException: Unsupported TIFF PhotometricInterpretation value: 32803 reading DNG file

### ISSUE THREAD

**Issue by rnoel1962** [haraldk/TwelveMonkeys#563]
I am trying to read a DNG file generated from my Samsung Galaxy 9 phone and get the following exception:

javax.imageio.IIOException: Unsupported TIFF PhotometricInterpretation value: 32803
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getOpaqueSamplesPerPixel(TIFFImageReader.java:748)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getRawImageType(TIFFImageReader.java:446)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getImageTypes(TIFFImageReader.java:871)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:900)
...

Is this DNG format supported?  If not, any idea when it might be?

**Comment by haraldk** [comment]
Hi,

DNG or Digital Negative is a camera RAW format based on the TIFF standard, so the TIFF plugin can parse it. However, the format extends the TIFF spec in ways not supported by the current implementation. So, the exception message basically answers your question (DNG is not supported). 

Your image contains CFA image data, that needs special treatment. If you like to implement support for it, I'm ready to accept a PR. Or if you like to sponsor the development of DNG support, that would also be very much appreciated. 


Best regards,

-- 
Harald K
