### ISSUE TITLE
Incorrect Exif metadata may cause OOME Part 2

### ISSUE THREAD

**Issue by kmittig** [haraldk/TwelveMonkeys#578]
Hey there,

it seems that there is still a problem with broken Exif metadata in TIFF images. I recently stumbled upon #574 and thought I was lucky, because it got fixed. But I've got a corrupted image of 10 MB size that causes an OOME and it still does with the new code from #574. I'm not super deep into the TIFF specification, but I can tell, that some part of the Exif metadata is wrong. The image itself can, however, be displayed by any viewer I've tried.

The OOME happens at

```
TiffReader.readValue(ImageInputStream, short, int, boolean)
...
case TIFF.TYPE_SSHORT
...
short[] shorts = new short[pCount];
```

where pCount is 604110848 which equals an array of ~1.12 GB. The system I'm working on provides only 650 MB heap space for the VM (a limitation I cannot change), and therefore I get the following error:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readValue(TIFFReader.java:384)
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readValueAt(TIFFReader.java:324)
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readEntry(TIFFReader.java:298)
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:146)
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readSubIFDs(TIFFReader.java:188)
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readIFD(TIFFReader.java:158)
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.readLinkedIFDs(TIFFReader.java:120)
 at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.read(TIFFReader.java:109)
```

I really don't know what is wrong with this image, but I think, TwelveMonkeys should still be able to read it without having the need to pump up heap size above 1 GB. Can anyone take a look into this matter?

Additional notes:
- ExifTool shows: "Warning - Bad ExifIFD directory"
- ImageMagick identify shows: "identify.exe: Sanity check on directory count failed, this is probably not a valid IFD offset. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/661.
identify.exe: Failed to read custom directory at offset 10621056. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/661."
- I'm using TwelveMonkeys 3.4.1 (couldn't find any difference in this matter in 3.6.1) and Java 8.

[corruptedMetadata.zip](https://github.com/haraldk/TwelveMonkeys/files/5690012/corruptedMetadata.zip)

**Comment by haraldk** [comment]
Hi,

The issue you mention (#574) was quite recently reported, and is fixed in 3.6.1. 
I tried and your image reads just fine with as little as 32MB heap (using `-Xmx32m`).


-- 
Harald K
