### ISSUE TITLE
Infinite loop on corrupt jpeg

### ISSUE THREAD

**Issue by tballison** [haraldk/TwelveMonkeys#595]
In trying to break PDFBox via embedded corrupt jpegs, I found an infinite loop in twelvemonkeys.  Many thanks to Tilman Hausherr for helping me replicate this with the unembedded jpeg and for recommending testing with TwelveMonkeys.

File:
![extracted](https://user-images.githubusercontent.com/6739646/110115680-6d6dce80-7d84-11eb-99df-4cb21df3b09f.jpeg)

```
        Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("JPEG");
        ImageReader reader = null;
        while (readers.hasNext()) {
            reader = readers.next();
            break;
        }
        try (InputStream is = Files.newInputStream(p)) {
            ImageInputStream iis = ImageIO.createImageInputStream(is);

            reader.setInput(iis);
            ImageReadParam irp = reader.getDefaultReadParam();

            Raster raster;
            try {
                BufferedImage image = reader.read(0, irp);
                raster = image.getRaster();
            } catch (IIOException var20) {
                raster = reader.readRaster(0, irp);
            }
        }
```

**Comment by tballison** [comment]
```
       <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-jpeg</artifactId>
            <version>3.6.3</version>
        </dependency>
```

```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```

**Comment by haraldk** [comment]
Thanks for reporting!

Have you looked into the code more deeply to see why this happens or any suggestions for a fix? 😀 

Either way, I'll look into it. 

-- 
Harald K

**Comment by tballison** [comment]
```
end:471, JPEGSegmentImageInputStream$Segment (com.twelvemonkeys.imageio.plugins.jpeg)
repositionAsNecessary:385, JPEGSegmentImageInputStream (com.twelvemonkeys.imageio.plugins.jpeg)
read:423, JPEGSegmentImageInputStream (com.twelvemonkeys.imageio.plugins.jpeg)
readInputData:312, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readImageHeader:-1, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readNativeHeader:731, JPEGImageReader (com.sun.imageio.plugins.jpeg)
checkTablesOnly:347, JPEGImageReader (com.sun.imageio.plugins.jpeg)
gotoImage:496, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readHeader:724, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readInternal:1130, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readRaster:1541, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readRaster:1056, JPEGImageReader (com.twelvemonkeys.imageio.plugins.jpeg)
main:39, TwelveMonkeysMetadata (org.tallison.pdfbox.images)
```
My guess is `repositionAsNecessary` is resetting to an infinite loop.

**Comment by tballison** [comment]
var5 can == 0, which means nothing is read.
read:581, JPEGSegmentImageInputStream$ReplacementSegment (com.twelvemonkeys.imageio.plugins.jpeg)
read:426, JPEGSegmentImageInputStream (com.twelvemonkeys.imageio.plugins.jpeg)
readInputData:312, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readImageHeader:-1, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readNativeHeader:731, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readHeader:725, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readInternal:1130, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readRaster:1541, JPEGImageReader (com.sun.imageio.plugins.jpeg)
readRaster:1056, JPEGImageReader (com.twelvemonkeys.imageio.plugins.jpeg)
main:39, TwelveMonkeysMetadata (org.tallison.pdfbox.images)
![Screenshot from 2021-03-05 08-09-54](https://user-images.githubusercontent.com/6739646/110119972-72ce1780-7d8a-11eb-81d3-cdc4786de166.png)
![Screenshot from 2021-03-05 08-08-59](https://user-images.githubusercontent.com/6739646/110119973-7366ae00-7d8a-11eb-9135-f9173cf3aab1.png)

**Comment by tballison** [comment]
![Screenshot from 2021-03-05 08-25-53](https://user-images.githubusercontent.com/6739646/110121495-74004400-7d8c-11eb-9d72-848515208109.png)

Y, streamPos never progresses.

**Comment by haraldk** [comment]
@tballison Thanks! Great input! 

I've worked your code into a failing test case, and will create a fix as soon as possible. 😀

-- 
Harald K

**Comment by haraldk** [comment]
I've pushed a fix for the issue, would be great if you could create a local build and verify that it work.

Also, let me know if you have more JPEGs that cause similar issues! 😀 

Again, thanks for your valuable work on debugging this!

-- 
Harald K

**Comment by tballison** [comment]
Hmmm...I'm not able to build from master...
![Screenshot from 2021-03-08 10-41-39](https://user-images.githubusercontent.com/6739646/110343896-f1c98700-7ffa-11eb-9733-020517cc3deb.png)

java.lang.AssertionError: ImageTypeSpecifier from getRawImageType should be in the iterator from getImageTypes

	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.twelvemonkeys.imageio.util.ImageReaderAbstractTest.testGetTypeSpecifiers(ImageReaderAbstractTest.java:1384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

**Comment by tballison** [comment]
Let me ignore that test and give it a go!

**Comment by tballison** [comment]
Separate topic...are you interested in runtime exceptions like this?  Will open separate issues for these.  If this is expected, I'll keep them to myself.  :D 

Many thanks!

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 31741
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGLosslessDecoder.getHuffmanValue(JPEGLosslessDecoder.java:557)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGLosslessDecoder.decodeSingle(JPEGLosslessDecoder.java:364)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGLosslessDecoder.decode(JPEGLosslessDecoder.java:319)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGLosslessDecoder.decode(JPEGLosslessDecoder.java:233)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGLosslessDecoderWrapper.readImage(JPEGLosslessDecoderWrapper.java:85)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGLosslessDecoderWrapper.readRaster(JPEGLosslessDecoderWrapper.java:114)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readRaster(JPEGImageReader.java:1025)
	at org.apache.pdfbox.filter.DCTFilter.decode(DCTFilter.java:105)
```

**Comment by haraldk** [comment]
You might need an Oracle JDK to build. But don't worry too much, I've run the tests and they all pass, both local and CI (Travis). 😀 

For the exceptions, feel free to file them as separate issues! In a perfect world, all problems with malformed input should be reported as `IIOException`s, however in real life it may be impractical for performance reasons. It's not a huge problems like the endless loop. 

In any case, I'm interested and will look into it, if you send me the files.


Thanks,

-- 
Harald K
