### ISSUE TITLE
Tif Image reading produces IIOException: Unsupported element precision

### ISSUE THREAD

**Issue by flohauer** [haraldk/TwelveMonkeys#598]
I tried several ways but got this problem.

openJDK  11, and tif Files from the attachment
 
```
javax.imageio.IIOException: Unsupported element precision
	at com.sun.imageio.plugins.jpeg.DQTMarkerSegment$Qtable.<init>(DQTMarkerSegment.java:227)
	at com.sun.imageio.plugins.jpeg.DQTMarkerSegment.<init>(DQTMarkerSegment.java:61)
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:195)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:359)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getStreamMetadata(JPEGImageReader.java:1018)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1144)
```
example code:

```java
try (InputStream is = new FileInputStream(file)) {
	final ImageInputStream input;
	ImageReader reader = null;
	input = ImageIO.createImageInputStream(is);
	final Iterator<ImageReader> readerIT = ImageIO.getImageReaders(input);
	if (readerIT.hasNext())
		reader = readerIT.next();
	if (reader != null) {
		reader.setInput(input);
		final int images = reader.getNumImages(false);
		for (int i = 0; i < images; i++) {
			BufferedImage image = null;
			final IIOMetadata meta = reader.getImageMetadata(i);
			System.out.println(Arrays.toString(meta.getMetadataFormatNames()));
		        image = reader.read(i, reader.getDefaultReadParam());
		        ...
```

[tif_examples.zip](https://github.com/haraldk/TwelveMonkeys/files/6180644/tif_examples.zip)
(test files from our customer)

**Comment by haraldk** [comment]
Hi,

I tried your images here, and both files in your ZIP could be read fine, using the TwelveMonkeys TIFF and JPEG plugins. 

- `P00118032100013406.tif` is a black/white image with CCITT T6 (compression 4) encoding and should not produce the above exception. 
- `B00118032100013406.tif` on the other hand, is a color image with JPEG compression (compression 7), and may cause the above exception, without the TwelveMonkeys JPEG plugin installed, as it contains 16 bit DQT (quantization tables). JPEG decoding in TIFF files is delegated to the JPEG plugin, but I see from the stack trace that the JPEG decoding is performed by the `com.sun....JPEGImageReader`. Try with the TwelveMonkeys JPEG plugin installed, and you should be good. 


Best regards,

-- 
Harald K

**Comment by flohauer** [comment]
You are right the `P00118032100013406.tif` is an other type and works fine with my code. I ordered these test-files for this Issue but only checked the B001... file sry for that. 

I`ll try the TwelveMonkeys JPEG plugin for the `B00118032100013406.tif`.

Thank you for your help.

Best regards,

Florian Hauer

**Comment by haraldk** [comment]
Closing for now. Feel free to re-open if you have further problems reading this file using the TwelveMonkeys TIFF and JPEG plugins, or file a new issue for other problems. 

-- 
Harald K
