### ISSUE TITLE
OutOfMemoryError occurs when reading a large JPG with CMYK format

### ISSUE THREAD

**Issue by linglq** [haraldk/TwelveMonkeys#615]
OutOfMemoryError came up as I tried to read a JPG with CMYK format, which is 98M large. 

**Version information**
1. TwelveMonkeys version 3.7.0.

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

3. MacOS Big Sur, 64-bit

**Example code**
Here's my code
BufferedImage img = null;
        ImageInputStream input = ImageIO.createImageInputStream(src);

        // Get the reader
        Iterator<ImageReader> readers = ImageIO.getImageReaders(input);
        // 尝试所有的 reader
        while (readers.hasNext()) {
            ImageReader reader = readers.next();
            reader.setInput(input);
            ImageReadParam param = reader.getDefaultReadParam();

            try {
                for (Iterator<ImageTypeSpecifier> it = reader.getImageTypes(0); it.hasNext(); ) {
                    ImageTypeSpecifier type = it.next();
                    if (type.getColorModel().getColorSpace().getType() == ColorSpace.TYPE_CMYK) {
                        param.setDestinationType(type);
                        break;
                    }
                }

                img = reader.read(0, param);
                break;
            }  catch (IOException e) {
                e.printStackTrace();
            } finally {
                reader.dispose();
            }
        }

**Sample file(s)**
the JPG file is 98M, in resolution 14173 × 17074.But it can't be uploaded.

**Stak trace**
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:76) ~[na:1.8.0_231]
	at java.awt.image.Raster.createInterleavedRaster(Raster.java:266) ~[na:1.8.0_231]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1176) ~[na:1.8.0_231]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readRaster(JPEGImageReader.java:1479) ~[na:1.8.0_231]
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(JPEGImageReader.java:496) ~[imageio-jpeg-3.7.0.jar:3.7.0]
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:346) ~[imageio-jpeg-3.7.0.jar:3.7.0]
	at com.cnblind.photocut.utils.ImageUtils.resize(ImageUtils.java:123) ~[classes/:na]
	at com.cnblind.photocut.utils.ImageUtils.webImage(ImageUtils.java:168) ~[classes/:na]
	at com.cnblind.photocut.utils.FileWatchRunner$1.visitFile(FileWatchRunner.java:99) ~[classes/:na]
	at com.cnblind.photocut.utils.FileWatchRunner$1.visitFile(FileWatchRunner.java:75) ~[classes/:na]
	at java.nio.file.Files.walkFileTree(Files.java:2670) ~[na:1.8.0_231]
	at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_231]
	at com.cnblind.photocut.utils.FileWatchRunner.lambda$startRecursiveWatcher$0(FileWatchRunner.java:75) ~[classes/:na]
	at com.cnblind.photocut.utils.FileWatchRunner$$Lambda$851/1605154309.accept(Unknown Source) ~[na:na]
	at com.cnblind.photocut.utils.FileWatchRunner.startRecursiveWatcher(FileWatchRunner.java:111) ~[classes/:na]
	at com.cnblind.photocut.utils.FileWatchRunner.run(FileWatchRunner.java:58) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.2.jar:2.5.2]
	at com.cnblind.photocut.Application.main(Application.java:28) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.5.2.jar:2.5.2]

**Comment by haraldk** [comment]
Hi @linglq 

An image file of those dimensions in CMYK format will need at least 14173  *  17074 * =  967959208 bytes (~923 MB) of *contiguous heap memory*. Due to limitations in the native JPEG decoder, you will probably need twice that amount. 

Running out of memory due to large images is not a bug. As the requirement is that the entire block of memory is contiguous (a requirement of arrays in Java), it's possible to see this happen, even if you have more than 1GB of free memory. Typically, this happens as the Java heap gets "fragmented" or "polluted" after a while.

The easy fix is just to restart the Java VM, possibly increasing the max memory using the `-Xmx` flag. It's also possible to require less memory by subsampling or reading a subregion of the image, if this is an option to you (your stack trace indicates resizing, so subsampling should be a good candidate). Finally, it's possible to create a custom `DataBuffer` implementation that does not require a single continuous array, but I don't think it will help in this particular case, as the raster/buffer is allocated by the JDK code. 


Best regards,

-- 
Harald K

**Comment by linglq** [comment]
hi Harald, thanks for responsing.
Sorry that I should tag the post 'trouble-shooting' instead of BUG. And I tried to restart the application by add an option -Xmx2048m to increase available memory, but the error is still. My plan is to resize the large image to small size. And I can't figure out how to do it under this situation. Can you give me some advice?

**Comment by linglq** [comment]
hi @haraldk , thanks for responsing.
Sorry that I should tag the post 'trouble-shooting' instead of BUG. And I tried to restart the application by add an option -Xmx2048m to increase available memory, but the error is still. My plan is to resize the large image to small size. And I can't figure out how to do it under this situation. Can you give me some advice?

**Comment by haraldk** [comment]
>  Can you give me some advice?

I believe I already did... 😀 

> [...] you will probably need twice that amount

As I mentioned, you might need two 923 MB blocks of contiguous memory (that is > 1.8 GB) . Setting max to 2 GB might not be enough for this, as there's hardly room for anything else. You might need 3 to 4 GB to be sure. 

>  It's also possible to require less memory by subsampling or reading a subregion of the image, if this is an option to you (your stack trace indicates resizing, so subsampling should be a good candidate)

Did you try reading using subsampling? Even using subsampling factors of only 2 in each dimension, will reduce the memory usage about 75%.  I don't know what output size you are aiming for, but with such a huge image it may not even be visible in the end quality. This really is my best advice.


Regards,

-- 
Harald K

**Comment by linglq** [comment]
@haraldk Thanks again. Yep I tried -Xmx4000m, but It turned out the same. Tricky.... I haven't tried the subsampling way. The output size I want is about 1200x1200, will that be good enough?

**Comment by haraldk** [comment]
Your input image of 14173  x  17074 has more than 10 times the pixels in each dimension, so yes, it will be more than good enough. 

-- 
Harald K
