### ISSUE TITLE
Found a failing TIFF file

### ISSUE THREAD

**Issue by KoenDG** [haraldk/TwelveMonkeys#626]
**Describe the bug**
A TIFF file is failing to be read.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.7.0

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment Corretto-8.222.10.1 (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM Corretto-8.222.10.1 (build 25.222-b10, mixed mode)
```

I added the file on my local branch, it can be found there, I accidentally made a PR first: https://github.com/haraldk/TwelveMonkeys/pull/625

The file: https://github.com/KoenDG/TwelveMonkeys/blob/1031364e6ca4ef4126837d99e154e3cd22b8075c/imageio/imageio-tiff/src/test/resources/bigtiff/G32DS.tif

**Expected behavior**
The file is processed normally.

**Stak trace**
```
java.io.IOException: Unknown code in Huffman RLE stream
        at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decodeRun(CCITTFaxDecoderStream.java:445)
        at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decode1D(CCITTFaxDecoderStream.java:227)
        at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decodeRowType2(CCITTFaxDecoderStream.java:331)
        at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decodeRow(CCITTFaxDecoderStream.java:373)
        at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.fetch(CCITTFaxDecoderStream.java:198)
        at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.read(CCITTFaxDecoderStream.java:524)
        at java.io.DataInputStream.readFully(DataInputStream.java:195)
        at java.io.DataInputStream.readFully(DataInputStream.java:169)
        at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1878)
        at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1102)
```

**Comment by haraldk** [comment]
Thanks Koen,

It's another case of the TIFF reader being too "smart", second guessing the compression type encoded in the file, and reverting to use CCITT Huffman RLE (TIFF compression type 2) instead of T.4/G3 (type 3). See for example #579. It reads fine if I disable that extra check.

I'll see if we can make this detection even stronger. @Schmidor chime in as well, if you have any further insight or suggestions! 😀 

Best regards,

--
Harald K

**Comment by haraldk** [comment]
Okay,

Actually, I found that the current implementation for detection was a little too eager, so it tried to guess the correct encoding for each strip/tile. This means the effective decompression type could (and did, in this case) change mid-flight... 

I just pushed a fix that will try to guess only once per image, along with some minor other changes, and it works fine for this sample image.

-- 
Harald K

**Comment by Schmidor** [comment]
Okay, finally I understood the problem with the detection algorithm:
findCompressionType does not respect the fillOrder and so reads the bits within the bytes in the wrong order.

Oliver

**Comment by haraldk** [comment]
Cool, 

Looks like we found multiple issues, but nothing's better than fixing them both. 😀 

I think your fix is more important though, as I had a sneaking feeling my fix would fail on some inputs... Does that mean we can reduce the limit when searching for EOLs? 

-- 
Harald K

**Comment by Schmidor** [comment]
I got suspicious when the detector read much more bytes till the first EOL than the `decodeRow ` later did. 
As far as I can tell it is now back to only searching for EOLs back in the old files which caused writing the detector. So reducing the limit back to a few bytes should be enough.

Oliver

**Comment by haraldk** [comment]
Excellent!

Thanks @KoenDG & @Schmidor 👍🏻
