### ISSUE TITLE
JPEG metadata always read-only

### ISSUE THREAD

**Issue by ojaha065** [haraldk/TwelveMonkeys#668]
Greetings. I'm trying to read and modify metadata of JPEG images. Let's look at the following (heavily simplified) code:

```
try (final Closeable imageInputStream = ImageIO.createImageInputStream(new File("D:\\testImage.jpg"))) {
  final ImageReader reader = ImageIO.getImageReaders(imageInputStream).next();
  reader.setInput(imageInputStream);

  final IIOImage imageAndMeta = reader.readAll(0, reader.getDefaultReadParam());
  reader.dispose();

  final IIOMetadata metadata = imageAndMeta.getMetadata();

  final Node root = new IIOMetadataNode("javax_imageio_jpeg_image_1.0");
  root.appendChild(new IIOMetadataNode("JPEGvariety"));
  root.appendChild(new IIOMetadataNode("markerSequence"));
  //root.appendChild(...somethingElse...)

  metadata.mergeTree("javax_imageio_jpeg_image_1.0", root);
} catch (final Exception error) {
  error.printStackTrace();
}
```

It works fine without TwelveMonkeys, but throws an error (only) when TwelveMonkeys is installed:
```
java.lang.IllegalStateException: Metadata is read-only
	at com.twelvemonkeys.imageio.AbstractMetadata.assertMutable(AbstractMetadata.java:117) ~[imageio-core-3.8.1.jar:3.8.1]
	at com.twelvemonkeys.imageio.AbstractMetadata.mergeTree(AbstractMetadata.java:96) ~[imageio-core-3.8.1.jar:3.8.1]
	...
```

It seems that the metadata is always read-only and thus mergeTree function does not work. I've looked into this with debugger and it seems that in TwelveMonkeys' `JPEGImage10Metadata.java` `isReadOnly()` always returns true while in the original `com.sun.imageio.plugins.jpeg.JPEGMetadata` it's always false. Any idea why is this and how could I get around this?

**Comment by haraldk** [comment]
Hi Jani,

It would help my understanding if you describe what the use case is here, ie. what will you use the merged metadata for. 😀 

In any case, the metadata is read-only for now, as there hasn't been any need to merge. It's non-trivial, but probably not too hard to implement `mergeTree`, if you would like to have a go. 

Without actually making the metadata mutable and implementing `mergeTree`, one option could be to simply create an empty instance of `com.sun.imageio.plugins.jpeg.JPEGMetadata` and use `setFromTree`. But keep in mind that I created the `JPEGImage10Metadata` class because the standard class does not support a lot of in-the-wild JPEGs, so it may not work for all cases...

**Comment by davidekholm** [comment]
We're also facing problems with this in jAlbum 29 since we moved from using v3.5 to v3.8.1 of your lib. In our case it's the setFromTree() call that triggers this error. We're also including the original EXIF data with generated image as a user option, but this no longer works. The reason why we call setFromTree is that we have to modify the tree a bit for some JPEG images in order to avoid errors when including the metadata for some images. I've attached one such image, it triggers an "javax.imageio.metadata.IIOInvalidTreeException: Invalid DHT node" exception if we simply include the original IIOMetadata object when writing the new scaled file.

![priscilla-du-preez](https://user-images.githubusercontent.com/2260296/194860280-154dfc35-9125-402f-a66e-cb03ca2d5ffc.jpg)

**Comment by haraldk** [comment]
@davidekholm I'm not able to reproduce the problem with the JPEG you provided. It does not seem to be a problem with the DHT node, and I don't find any EXIF data either... Can you double check that the file is the correct one, and that GitHub upload does not "fix" the file for us? 😉 

If the file is as intended, can you please send me the code you use? I think I should be able to provide a workaround in any case.

**Comment by davidekholm** [comment]
Hi Harald. I've updated to v3.8.3 and the "Invalid DHT node" error is indeed gone now. Thank you.

**Comment by davidekholm** [comment]
Thanks Harald, so this will copy the EXIF data only?

**Comment by haraldk** [comment]
No, it gives you a mutable JPEG metadata, so you can copy whatever you like (what this issue is about).

---

Copying only Exif is (probably) possible, but tedious..

To copy only the Exif segment, you need to look at the `"markerSequence"`, get all the `"unknown"` nodes, and get the ones with `"MarkerTag"` value `"225"` (APP1/`0xFFE1`). There might be other APP1 markers beside Exif, so you probably need to look into the `userObject`, which for all `"unknown"` segments will contain a `byte` array. For Exif, this will start with the string `Exif\0\0` (and be followed by the TIFF structure).

Sadly, there is a bug in the JDK metadata, that inserts multiple `"unknown"` markers when you merge... 😕
