### ISSUE TITLE
PSD reader fails from 3.8.3 on (3.8.2 works)

### ISSUE THREAD

**Issue by Traktormaster** [haraldk/TwelveMonkeys#716]
**Describe the bug**
Opening of a specific PSD file has broken in 3.8.3 and it is still broken in 3.9.3.

I'm using a tiny servlet server with Javalin and Jetty as a network-worker service to create thumbnails of files PUT to an endpoint with the Thumbnailator library. By only changing the versions of the TwelveMonkeys image plugins reintroduces/fixes the issue, I do not think any other dependency I use is the culprit.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.

   3.8.2 works, 3.8.3 and 3.9.3 do not work (I'd guess versions in between are affected as well)

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
	openjdk version "11.0.17" 2022-10-18
	OpenJDK Runtime Environment (build 11.0.17+1)
	OpenJDK 64-Bit Server VM (build 11.0.17+1, mixed mode)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

    Arch Linux, I'm building a standalone JAR distribution with Maven.

**To Reproduce**
I can only provide the specific PSD file that's producing the issue right now.

I don't really know how to provide my sources for easy reproduction, so I hope the sample file is enough. If necessary I'll try and provide some reproducing source-code.

**Expected behavior**
The PSD file should be opened successfully.

**Sample file(s)**
[sample_640×426.psd.zip](https://github.com/haraldk/TwelveMonkeys/files/10050580/sample_640x426.psd.zip)
Originally from:
https://filesamples.com/samples/image/psd/sample_640%C3%97426.psd
SHA256: 58be12be3ff6b05b4cdba8211cd466d9a307a9fe02819b308fae8256f9cccf74  sample_640×426.psd

**Stak trace**
Trace with 3.8.3, but I've checked and it is the same with 3.9.3 as well:
```
[JettyServerThreadPool-19] WARN io.javalin.Javalin - Uncaught exception
java.lang.IllegalArgumentException: length < 0: -1
	at com.twelvemonkeys.lang.Validate.isTrue(Validate.java:197)
	at com.twelvemonkeys.imageio.stream.SubImageInputStream.<init>(SubImageInputStream.java:65)
	at com.twelvemonkeys.imageio.plugins.psd.PSDUtil.createDecompressorStream(PSDUtil.java:106)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readImageData(PSDImageReader.java:470)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:429)
	at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.readImage(Unknown Source)
	at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.read(Unknown Source)
	at com.foobar.Foobar.lambda$main$3(Foobar.java:117)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Thank you for the library and I hope to see this fixed soon as well!

**Comment by haraldk** [comment]
Hi! I believe this is the same issue as #713. 

It’s fixed, but not yet released. Can you try again using the latest snapshot?

**Comment by Traktormaster** [comment]
You're right! I can confirm that snapshot build of current master (a3a30d5) can open the sample PSD file. I'll be waiting for the new release then.

Thank you!

**Comment by haraldk** [comment]
Thanks for verifying! 👍🏻

**Comment by haraldk** [comment]
3.9.4 release is out.
