### ISSUE TITLE
Fail to generate PNG file from PSD when update 3.6.1 to 3.9.4

### ISSUE THREAD

**Issue by dsboo** [haraldk/TwelveMonkeys#719]
**Describe the bug**

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.
CentOS Linux 7 (Core)

**To Reproduce**

1. Open PSD file in java code
2. make BufferedImage from PSD file

**Expected behavior**
generate PNG file from PSD normally

**Example code**
If you need, i will write unit test code.

**Sample file(s)**
I cannot attached, because it's customer's.

**Stak trace**
```
java.util.EmptyStackException: null
  at java.base/java.util.Stack.peek(Stack.java:102)
  at java.base/java.util.Stack.pop(Stack.java:84)
  at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readLayerInfo(PSDImageReader.java:1051)
  at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readLayerAndMaskInfo(PSDImageReader.java:920)
  at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getNumImages(PSDImageReader.java:1220)
  at com.twelvemonkeys.imageio.ImageReaderBase.checkBounds(ImageReaderBase.java:190)
  at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:368)
  at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
  at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
```

**Additional context**
When I use 3.6.1 version, always success to generate PNG file from PSD.
But When I use 3.9.4 latest version, always fail to generate PNG file from PSD.
If you need more infomation, tell me freely.

**Comment by haraldk** [comment]
Thanks for reporting! 

I can see from the stack trace that this happens during reading of the PSD (layer info), it's not directly related to the conversion to PNG format.  But, there's something with the grouping of the layers in the file you use, that is either non-spec or we don't handle it properly... Probably the latter. Layer group support was introduced in 3.9.0, so I guess any version below that will work. 

Unfortunately, I can't say much more without having a sample image, or at least a dump of the layer structure. All my sample files can be converted using that code (assuming `inputStream` and `targetStream` should be the same, and replacing code I don't have). 

Are you able to export a copy of the file with the image data removed (but the layer structure intact)? Or if you can create a PSD with a similar layer structure that also expose this problem, that would also help.

**Comment by haraldk** [comment]
Closing as not reproducible. Please reopen if you find a sample that can be shared.

**Comment by EvanDarwin** [comment]
@haraldk I'm currently able to reproduce this issue on `imageio-psd 3.9.4` (`OpenJDK 18.0.2.1`), and am able to provide a repro sample as well. 

I have no reason to believe this file was created in a client other than modern Photoshop. Any time you could take to investigate this would be appreciated. 😄 

**Stack trace:**
```
Exception in thread "main" java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readLayerInfo(PSDImageReader.java:1051)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readLayerAndMaskInfo(PSDImageReader.java:970)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getNumImages(PSDImageReader.java:1220)
	at com.twelvemonkeys.imageio.ImageReaderBase.checkBounds(ImageReaderBase.java:190)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getHeight(PSDImageReader.java:112)
``` 

**Asset:**
[repro.psd.zip](https://github.com/haraldk/TwelveMonkeys/files/12131484/repro.psd.zip)

**Comment by haraldk** [comment]
Hmm.. Sorry, I missed that you had submitted a way to reproduce this... However, I'm unable to reproduce the issue with the above code and attached file on the current master branch. So it seems the issue is resolved through some other fix. 😀
