### ISSUE TITLE
WebP reader not working

### ISSUE THREAD

**Issue by popov654** [haraldk/TwelveMonkeys#720]
I am trying to test WebP plugin in my project, that is using Java 7. I made a simple JPanel where I am trying to render a WebP image from YouTube video cover.

I built everything following the instructions, but after I lanch the code, I get the followong error:

```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
        at com.twelvemonkeys.imageio.stream.BufferedChannelImageInputStream.fillBuffer(BufferedChannelImageInputStream.java:155)
        at com.twelvemonkeys.imageio.stream.BufferedChannelImageInputStream.read(BufferedChannelImageInputStream.java:197)
        at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:351)
        at com.twelvemonkeys.imageio.stream.BufferedChannelImageInputStream.readInt(BufferedChannelImageInputStream.java:299)
        at com.twelvemonkeys.imageio.plugins.webp.WebPImageReaderSpi.canDecode(WebPImageReaderSpi.java:65)
        at com.twelvemonkeys.imageio.plugins.webp.WebPImageReaderSpi.canDecodeInput(WebPImageReaderSpi.java:54)
        at javax.imageio.ImageIO$CanDecodeInputFilter.filter(ImageIO.java:567)
        at javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:810)
        at javax.imageio.spi.FilterIterator.<init>(ServiceRegistry.java:804)
        at javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:508)
        at javax.imageio.ImageIO.getImageReaders(ImageIO.java:646)
        at javax.imageio.ImageIO.read(ImageIO.java:1438)
        at javax.imageio.ImageIO.read(ImageIO.java:1400)
        at render.TestWebPImage.<init>(TestWebPImage.java:22)
        at render.TestWebPImage.main(TestWebPImage.java:41)
```

Version: 3.10.0

java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

OS: Windows 7 x64 Pro SP1

Test code:

```java
public class TestWebPImage extends JFrame {
    public TestWebPImage() {
        super("WebP reader test");
        try {
            image = ImageIO.read(new URL("https://i.ytimg.com/vi_webp/-gCxI3G_GkY/maxresdefault.webp"));
        } catch (IOException ex) {
            Logger.getLogger(TestWebPImage.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPanel test = new JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                Graphics2D g2d = (Graphics2D) g;
                if (image != null) {
                    g2d.drawImage(image, 0, 0, null);
                }
            }
        };

        this.setContentPane(test);
        this.setLocationRelativeTo(null);
    }

    public static void main(String[] args) {
        TestWebPImage test = new TestWebPImage();
        test.setVisible(true);
    }

    BufferedImage image;
}
```

**Comment by haraldk** [comment]
It looks like the library has been accidentally compiled with Java 8. Some methods in the `Buffer`/`ByteBuffer` hierarchy was moved up/down between Java 7 and 8, and I think this is what causing the problem.

If possible, you can try upgrading to Java 8 (Java 7 is really old, but I guess you have some very good reasons for using it). The other option is to build the library from sources using Java 7.

I'll try to create a new version of the library built against Java 7 too, but it won't happen until next year. 😉

**Comment by popov654** [comment]
Can I somehow compile with Java 7 using Maven? How can I do this, by changing system default Java version?

Or is the problem in source code?

**Comment by haraldk** [comment]
The Maven POM specifies target JDK 1.7, and I don't think I have used any 1.8 libraries or features. So yes, just specify Java 7 (I think you might set `JAVA_HOME` to point to your Java 7 JDK), and issue `min clean package`.

**Comment by popov654** [comment]
Yes, I already set the env variable, seems it worked. But the build fails. I can only build `lang` subdirectory this way separately. If I build all, it fails on `servlet` subproject, which I don't even need...

I tried compiling just `imageio` or `imageio-webp`, but no luck.

**Comment by popov654** [comment]
```[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ servlet ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.043 s
<<< FAILURE! - in com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest

[ERROR] com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest.testConte
xtDestroyed  Time elapsed: 0.006 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/mockito/Mockito : Unsupported major.
minor version 52.0
        at com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest.testCo
ntextDestroyed(IIOProviderContextListenerTest.java:65)

[ERROR] com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest.testDestr
oyConcurrentModRegression  Time elapsed: 0 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/mockito/Mockito
        at com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest.testDe
stroyConcurrentModRegression(IIOProviderContextListenerTest.java:77)

[ERROR] com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest.testConte
xtInitialized  Time elapsed: 0.001 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/mockito/Mockito
        at com.twelvemonkeys.servlet.image.IIOProviderContextListenerTest.testCo
ntextInitialized(IIOProviderContextListenerTest.java:60)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   IIOProviderContextListenerTest.testContextDestroyed:65 ╗ UnsupportedCl
assVersion
[ERROR]   IIOProviderContextListenerTest.testContextInitialized:60 UnsupportedCl
assVersion
[ERROR]   IIOProviderContextListenerTest.testDestroyConcurrentModRegression:77 U
nsupportedClassVersion
[INFO]
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for TwelveMonkeys 3.10.0-SNAPSHOT:
[INFO]
[INFO] TwelveMonkeys ...................................... SUCCESS [  0.390 s]
[INFO] TwelveMonkeys :: Common ............................ SUCCESS [  0.024 s]
[INFO] TwelveMonkeys :: Common :: Language support ........ SUCCESS [  3.054 s]
[INFO] TwelveMonkeys :: Common :: IO ...................... SUCCESS [  1.827 s]
[INFO] TwelveMonkeys :: Common :: Image ................... SUCCESS [  2.325 s]
[INFO] TwelveMonkeys :: Servlet ........................... FAILURE [  0.290 s]
[INFO] TwelveMonkeys :: ImageIO ........................... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Core ................... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Metadata ............... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Photoshop Path Support . SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: BMP plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: HDR plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: ICNS plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: IFF plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: JPEG plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PCX plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PDF plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PICT plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PNM plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: PSD plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: SGI plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: TGA plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Thumbs.db plugin ....... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: TIFF plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: WebP plugin ............ SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: XWD plugin ............. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: Batik Plugin ........... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: JDK Reference Tests .... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: JPEG/JEP-262 Interop ... SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: JPEG/JAI TIFF Interop .. SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: TIFF/JAI Metadata Interop SKIPPED
[INFO] TwelveMonkeys :: ImageIO :: TIFF/JDK JPEG Interop .. SKIPPED
[INFO] TwelveMonkeys :: Contrib ........................... SKIPPED
[INFO] TwelveMonkeys :: BOM ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.480 s
[INFO] Finished at: 2022-12-30T14:11:16+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.
0.0-M5:test (default-test) on project servlet: There are test failures.
[ERROR]
[ERROR] Please refer to E:\TwelveMonkeys\servlet\target\surefire-reports for the
 individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].
dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <args> -rf :servlet```

**Comment by popov654** [comment]
Oh, I found a way to skip all tests by editing pom.xml. Thanks for help, it works now :)

**Comment by haraldk** [comment]
Hmmm.. 

Didn't realize the tests wouldn't run, but that should be no problem. I think using the `skipTests` flag with Maven should work, without editing the POM:  `mvn clean package -DskipTests`. Anyway, glad you could make it work! 👍🏻
