### ISSUE TITLE
Writing Tiff Throwing No Such Element Exception At final ImageWriter writer = imageWriters.next();

### ISSUE THREAD

**Issue by asadallap** [haraldk/TwelveMonkeys#726]
I am trying to merge multiple multi page tiff files into a single Tiff. I am using the below code,

```java
final File f = new File(OUTPUT_FOLDER + tiffFileName + ".tif");
final ImageOutputStream imageOutputStream = ImageIO.createImageOutputStream(f);

imageOutputStream.setByteOrder(ByteOrder.LITTLE_ENDIAN);
final Iterator<ImageWriter> imageWriters = ImageIO.getImageWritersByFormatName("tiff");

final ImageWriter writer = imageWriters.next();

writer.setOutput(output);
writer.prepareWriteSequence(null);

writer.setOutput(imageOutputStream);
ImageWriteParam param = writer.getDefaultWriteParam();
param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
param.setCompressionType("LZW");
param.setCompressionQuality(0.2f);

int pageCounter = 0;

for (PDPage page : pddocument.getPages()) {
	BufferedImage bim = pdfRenderer.renderImageWithDPI(pageCounter++, 48);
	writer.writeToSequence(new IIOImage(bim, null, null), param);
}

writer.endWriteSequence();
writer.dispose();
```

I am facing the below exception at Line-5 i.e **final ImageWriter writer = imageWriters.next();** 

```
java.util.NoSuchElementException
at javax.imageio.spi.FilterIterator.next(ServiceRegistry.java:849)
at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:842)
at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:827)
at mergeTiff.MergeTiffFile.MergeTiff_dev(MergeTiffFile.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.mule.extensions.java.internal.util.MethodInvoker.doInvoke(MethodInvoker.java:99)
at org.mule.extensions.java.internal.util.MethodInvoker.invokeMethod(MethodInvoker.java:85)
at org.mule.extensions.java.internal.util.MethodInvoker.invokeMethod(MethodInvoker.java:49)
at org.mule.extensions.java.internal.operation.JavaInvokeOperations.invokeStatic(JavaInvokeOperations.java:118)at org.mule.extensions.java.internal.operation.JavaInvokeOperations$invokeStatic$MethodComponentExecutor_.execute(Unknown Source) org.mule.runtime.module.extension.internal.runtime.execution.GeneratedMethodComponentExecutor.execute(GeneratedMethodComponentExecutor.java:94)
at org.mule.runtime.module.extension.internal.runtime.execution.CompletableMethodOperationExecutor.doExecute(CompletableMethodOperationExecutor.java:26)
at org.mule.runtime.module.extension.internal.runtime.execution.AbstractCompletableMethodOperationExecutor.execute(AbstractCompletableMethodOperationExecutor.java:61)
at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.executeCommand(DefaultExecutionMediator.java:237)
at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.executeWithInterceptors(DefaultExecutionMediator.java:221)
at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$execute$1(DefaultExecutionMediator.java:130)
at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$new$0(DefaultExecutionMediator.java:73)
at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.withExecutionTemplate(DefaultExecutionMediator.java:316)
at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.execute(DefaultExecutionMediator.java:129)
at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.executeOperation(ComponentMessageProcessor.java:581)
at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.prepareAndExecuteOperation(ComponentMessageProcessor.java:806)
at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.lambda$onEventSynchronous$16(ComponentMessageProcessor.java:483)
at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.onEventSynchronous(ComponentMessageProcessor.java:490)
at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.lambda$null$6(ComponentMessageProcessor.java:399)
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:482)
at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:496)
at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:511)
at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:506)
at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127)
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:351)
at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:178)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:151)
at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

```
FYI: Added the below maven dependency to POM.XML,

```xml
<dependency>
	<groupId>com.twelvemonkeys.imageio</groupId>
	<artifactId>imageio-tiff</artifactId>
	<version>3.9.4</version>
</dependency>
```

Note: I am invoking this method from Mule Cloudhub by using Invoke Static Java Method Operation & Cloudhub has Java 8. I hope by adding your plugin we can extend and get support for Tiff.

**Comment by haraldk** [comment]
Closing due to lack of input.
