### ISSUE TITLE
WebP: OOM for test file

### ISSUE THREAD

**Issue by BigMichi1** [haraldk/TwelveMonkeys#730]
**Describe the bug**
we have a sample webp file which causes an OOM and we want to understand if this is something we need to expect (reading webp files need a lot of memory) or if there is something not correct in the image reader.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
For example: 
```
    openjdk version "17.0.5" 2022-10-18
    OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
    OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
```

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

**To Reproduce**

1. Compile the below sample code
2. Download the sample image file
3. Run the code with the sample file and Xmx set to 1024m or lower

**Expected behavior**
should work with Xmx lower than 1280m

**Example code**
```
    @Test
    public void triggerOOM() throws IOException {
        try (final var file = new ClassPathResource("sample-webp-file-for-testing.webp").getInputStream()) {
            final var image = ImageIO.read(file);
            assertThat(image).isNotNull();
        }
    }
```

Less is more. Don't add your entire project, only the code required to reproduce the problem. 😀 

**Sample file(s)**
[sample-webp-file-for-testing.zip](https://github.com/haraldk/TwelveMonkeys/files/10464503/sample-webp-file-for-testing.zip)

**Stak trace**

      java.lang.OutOfMemoryError: Java heap space
        at com.twelvemonkeys.imageio.plugins.webp.vp8.MacroBlock.predictUV(MacroBlock.java:492)
        at com.twelvemonkeys.imageio.plugins.webp.vp8.MacroBlock.dequantMacroBlock(MacroBlock.java:211)
        at com.twelvemonkeys.imageio.plugins.webp.vp8.VP8Frame.decodeMacroBlockRow(VP8Frame.java:366)
        at com.twelvemonkeys.imageio.plugins.webp.vp8.VP8Frame.decode(VP8Frame.java:346)
        at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8(WebPImageReader.java:657)
        at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Extended(WebPImageReader.java:484)
        at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Extended(WebPImageReader.java:463)
        at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.read(WebPImageReader.java:441)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1470)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1365)

**Comment by haraldk** [comment]
Thanks for reporting!

While your WebP file is rather large (8000 x 6000 x 3 ~= 140 MB in memory), I have to agree that the memory requirements for decoding seem a bit unreasonable... 

I didn't write this code myself, so I don't know it with enough detail to say much about why the requirements are this high, or what can be done to optimize the memory usage. Any insights or suggestions at optimizations are very welcome!

**Comment by mcpierce** [comment]
I'm having a similar issue with running things on a Raspberry Pi box. My project's unit tests fail, but they pass on other platforms (MacOS, Windows, Linux).

**Comment by xudl33** [comment]
I‘m goted same issue at use mulity thread to read webp . I creaetd 20 threads to read nomal webp (only hundreds Kb，not too large )but is cost alot of heapspace to let my goted with OOM Exception.

TwelveMonkeys version 3.8.3

![image](https://github.com/user-attachments/assets/00945768-d626-4f8d-ae89-950656c2713a)

**Comment by haraldk** [comment]
Fixed via #1315
