### ISSUE TITLE
Exception when reading a tiled float32 BigTIFF

### ISSUE THREAD

**Issue by rfreeman853** [haraldk/TwelveMonkeys#746]
This code fragment raises an exception with some specific files:
```

    try {
      ImageInputStream input = ImageIO.createImageInputStream(file);
      ImageReader reader = ImageIO.getImageReaders(input).next();
      System.out.println( "Using reader: " + reader );

      reader.setInput(input);
      int width  = reader.getWidth(reader.getMinIndex());
      int height = reader.getHeight(reader.getMinIndex());
      System.out.println( "width, height: " + width + ", " + height );

      ImageReadParam param = reader.getDefaultReadParam();
      Rectangle rect = new Rectangle(256, 256, 2, 2);
      param.setSourceRegion(rect);
      System.out.println( "sourceRegion:    " + param.getSourceRegion().toString() );
      BufferedImage image = reader.read(0, param);
    }
    catch (Exception e) {
      System.out.println( "Exception:" );
      e.printStackTrace();
    }
```
When the requested rectangle is inside the initial tile in the image, the result is java.lang.ArrayIndexOutOfBoundsException with the message 'Coordinate out of bounds!'. Outside the first tile (as above) the output is:

```
Using reader: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@76ccd017
width, height: 58000, 66500
sourceRegion:    java.awt.Rectangle[x=256,y=256,width=2,height=2]
Exception:
java.awt.image.RasterFormatException: (parentX + width) is outside raster
        at java.desktop/java.awt.image.Raster.createChild(Raster.java:1526)
        at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.clipRowToRect(TIFFImageReader.java:1909)
        at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1094)
        at smallest_test.main(smallest_test.java:58)
```
The BigTIFF file is available from this page:
https://www.data.gov.uk/dataset/8311f42d-bddd-4cd4-98a3-e543de5be4cb/lidar-composite-dtm-2019-10m
Beware: the download is 3.6Gb; the file is 15.5Gb.

On that page, there is a message about a newer version of the BigTIFF. That file has the same effect. 

An observation: the number of pixels in the two files is between 2^31 and 2^32. That might cause a signed integer to become negative. No idea if that's useful.

**Comment by haraldk** [comment]
Thanks! 

I'll have a look! 

Update: Seems the server responds with `500 Internal Server Error` at the moment. I'll come by later...

**Comment by haraldk** [comment]
Okay, seems there is a bug in the `clipRowToRect` method in relation to a combination of source region and tiles... I'll find a fix.

**Comment by rfreeman853** [comment]
Thanks for your efforts on this!

**Comment by eomasters-repos** [comment]
I see this exception too. But on a normal GeoTiff. I use the file [spam2005v3r2_harvested-area_wheat_total.tiff.zip](https://github.com/GeoTIFF/test-data/blob/main/files/spam2005v3r2_harvested-area_wheat_total.tiff.zip)
During development I also got this exception:

`java.awt.image.RasterFormatException: (parentX + width) is outside raster at java.desktop/java.awt.image.Raster.createChild(Raster.java:1525) at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.clipRowToRect(TIFFImageReader.java:1932) at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1111) at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:947)`

## Environment
* TwelveMonkeys: com.twelvemonkeys.imageio:imageio-tiff:3.13.1
Java: GraalVM 25
OS: Win 11

## Observed Behavior
Calling reader.read(0, param) with:
* sourceRegion = Rectangle(0, 0, 128, 128)
* sourceBands = [0]
* destinationBands = [0]
throws one of:
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
java.awt.image.RasterFormatException: (parentX + width) is outside raster

## Minimal Snippet

```
ImageReader reader = ...; // TIFFImageReader via ImageIO
reader.setInput(iis, false, true);

ImageReadParam param = reader.getDefaultReadParam();
param.setSourceRegion(new Rectangle(0, 0, 128, 128));
param.setSourceBands(new int[]{0});
param.setDestinationBands(new int[]{0});

BufferedImage tile = reader.read(0, param); // throws

```

## Diagnostic Output (captured at failure)

```
[GeoTiffTileReader][DEBUG] Region read failed; dumping TIFF diagnostics
  time=2026-04-24T11:52:25.712446700Z
  file=D:\EOData\geotiff\spam2005v3r2_harvested-area_wheat_total.tiff
  reader=com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader
  twelvemonkeys.imageio-tiff.version=3.13.1
  ifdIndex=0
  requestedRegion=x:0,y:0,w:128,h:128
  bandIndex=0
  exception=java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
  imageSize=4320x1853
  tileSize(readerAPI)=128x128
  tag[256]=<absent>
  tag[257]=<absent>
  tag[278]=<absent>
  tag[273]=<absent>
  tag[279]=<absent>
  tag[322]=<absent>
  tag[323]=<absent>
  tag[324]=<absent>
  tag[325]=<absent>
  tag[284] PlanarConfiguration = [1]
  tag[277] SamplesPerPixel = [1]
  tag[258] BitsPerSample = [32]
  tag[339] SampleFormat = [3]
  tag[259] Compression = [1]
  tag[262] PhotometricInterpretation = [1]
  tag[254]=<absent>
  tag[274]=<absent>
  allPresentTags=258:BitsPerSample, 259:Compression, 262:PhotometricInterpretation, 266:FillOrder, 277:SamplesPerPixel, 282:XResolution, 283:YResolution, 284:PlanarConfiguration, 296:ResolutionUnit, 339:SampleFormat
```

## Note
As a workaround, reading the full image (reader.read(0, fullParam) without source region) and cropping in application code works for this file.

Maybe this helps

**Comment by hiSandog** [comment]
The later GeoTIFF report suggests this is not limited to the original tiny BigTIFF crop. A regression fixture should probably cover a tiled float image where the requested source region crosses a tile boundary and one where it sits entirely inside a tile, then assert the child raster bounds before creating the cropped raster. That would keep `clipRowToRect` from only being fixed for the 2x2 sample rectangle.
