### ISSUE TITLE
ClassCastException ImageReadParam BigTIFF reading

### ISSUE THREAD

**Issue by ebremer** [haraldk/TwelveMonkeys#795]
**Describe the bug**
Exception in thread "main" java.lang.ClassCastException: class javax.imageio.ImageReadParam cannot be cast to class javax.imageio.plugins.jpeg.JPEGImageReadParam (javax.imageio.ImageReadParam and javax.imageio.plugins.jpeg.JPEGImageReadParam are in module java.desktop of loader 'bootstrap')
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1188)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readTile(TIFFImageReader.java:2670)
        at com.ebremer.test.imagereader.NewClass.main(NewClass.java:38)

**Version information**

3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

openjdk version "20.0.2" 2023-07-18
OpenJDK Runtime Environment GraalVM CE 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b15)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b15, mixed mode, sharing)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

Windows 11

**To Reproduce**

Trying to read tile from large bigtiff

**Expected behavior**
Get a BufferedImage

**Example code**
BufferedImage image = reader.readTile(0, 0, 0);

**Comment by haraldk** [comment]
Glad you figured it out! Thanks for reporting back! 👍🏻
