### ISSUE TITLE
Support for TIFF with LZW with more than 12 bits per code

### ISSUE THREAD

**Issue by michal-niklas** [haraldk/TwelveMonkeys#84]
Hello,

One of TIFF images I tried to open with your plugin failed with exception:

com.twelvemonkeys.io.enc.DecodeException: TIFF LZW with more than 12 bits per code encountered (table overflow)
    at com.twelvemonkeys.imageio.plugins.tiff.LZWDecoder.addStringToTable(Unknown Source)
    at com.twelvemonkeys.imageio.plugins.tiff.LZWDecoder.decode(Unknown Source)
    at com.twelvemonkeys.io.enc.DecoderStream.fill(Unknown Source)
    at com.twelvemonkeys.io.enc.DecoderStream.read(Unknown Source)
    at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
    at com.twelvemonkeys.imageio.plugins.tiff.HorizontalDeDifferencingStream.fetch(Unknown Source)
    at com.twelvemonkeys.imageio.plugins.tiff.HorizontalDeDifferencingStream.read(Unknown Source)
    at java.io.DataInputStream.readFully(DataInputStream.java:195)
...

This TIFF opens without problems with GIMP, Krusader preview or with Pythons PIL library. It seems to be grayscale, 8 bits per pixel, LZW compression.

**Comment by haraldk** [comment]
FYI: This fix is included in the 3.0.2 release, and will be on Maven Central in a few hours. :-)

-- 
Harald K
