### ISSUE TITLE
Exception in LZWDecoder when reading tiff

### ISSUE THREAD

**Issue by twelvemonkeysissue** [haraldk/TwelveMonkeys#89]
Please rename the attached .png back to .tif. I added a .png extension to get around the attachment limitation.

Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:512)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:154)
	at com.twelvemonkeys.imageio.plugins.tiff.LZWDecoder$LZWString.writeTo(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.tiff.LZWDecoder.decode(Unknown Source)
	at com.twelvemonkeys.io.enc.DecoderStream.fill(Unknown Source)
	at com.twelvemonkeys.io.enc.DecoderStream.read(Unknown Source)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:221)
	at com.twelvemonkeys.imageio.plugins.tiff.HorizontalDeDifferencingStream.fetch(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.tiff.HorizontalDeDifferencingStream.read(Unknown Source)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(Unknown Source)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(Unknown Source)
	at javax.imageio.ImageReader.read(ImageReader.java:923)

![test 2 tif](https://cloud.githubusercontent.com/assets/10360202/5589977/f7f8472a-90ef-11e4-87a0-a71c858c9c3d.png)

**Comment by haraldk** [comment]
Hi,

Thanks for reporting! And +1 for creative circumvention of GitHub attachment limitation. I'll remember that for the future. :-)

It seems you are right, there's a problem reading the attached file. The problem is that it contains LZW decoded data, with some LZW strings longer than the scanline (containing multiple components)... I'm uncertain at the moment if this is a spec violation, but in any case, most software seems to read this so we should too. 

I think the fix is pretty easy to implement, so I will try to do that as soon as possible.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Fixed for master in 1d2f7d678fff8cb32b9a32bc58ceafe38b8bf59b

Also pushed to 3.0-bugfix branch.


Best regards,

-- 
Harald K

**Comment by twelvemonkeysissue** [comment]
Thank you for the quick fix. Which release will this be included in, 3.0.2 or 3.1? What is the timeline on that?

Thanks!

**Comment by haraldk** [comment]
The plan is to include it in both of those (unless I skip 3.0.2 and just release 3.1 right away). 

3.0.2 will be released asap. 3.1 a little later, but at least in January. I'd like to include a few more features in 3.1, but I might have to push some of it to 3.2. 


-- 
Harald K

**Comment by twelvemonkeysissue** [comment]
Great! Thanks for the info. Looking forward to 3.0.2. I need it asap.

**Comment by haraldk** [comment]
FYI: This fix is included in the 3.0.2 release, and will be on Maven Central in a few hours. :-)

-- 
Harald K
