### ISSUE TITLE
Webp: "Coordinate out of bounds!" exception thrown when loading a certain file

### ISSUE THREAD

**Issue by Parsee1** [haraldk/TwelveMonkeys#978]
**Describe the bug**

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
com.twelvemonkeys.imageio
imageio-webp
3.11.0

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
Java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.
JDK 17.0.1, IntelliJ Idea Community 2019.2.4, Win10 Home Basic

**To Reproduce**

1. Compile the below sample code
ImageIO.read(new URL("https://i0.hdslb.com/bfs/face/0266ce294d60018dcc6d567e57a3b93ae7825447.webp"));

2.Download the sample image file
https://i0.hdslb.com/bfs/face/0266ce294d60018dcc6d567e57a3b93ae7825447.webp

**Stak trace**
Always include the stack trace you experience.
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at java.desktop/sun.awt.image.ByteInterleavedRaster.setDataElements(ByteInterleavedRaster.java:541)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.decodeBwRef(VP8LDecoder.java:309)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.decodeImage(VP8LDecoder.java:225)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.readVP8Lossless(VP8LDecoder.java:131)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Lossless(WebPImageReader.java:673)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readAlpha(WebPImageReader.java:565)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Extended(WebPImageReader.java:498)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Extended(WebPImageReader.java:478)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.read(WebPImageReader.java:456)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1470)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1365)

**Comment by haraldk** [comment]
Hi @Parsee1,

Thanks for reporting! I'll investigate.

**Comment by haraldk** [comment]
Probably related to #734, #739 and  #785, but not necessarily the same issue.

**Comment by orDaor** [comment]
Hi guys, do you have any update on this bug? I encountered the same problem. Updating the webp plugin to 3.12.0 is not fixings this apparently.

**Comment by haraldk** [comment]
No, we haven't been able to fix this bug yet. 

It's mostly due to lack of time, so if you have some spare time to investigate to find the bug and/or fix it, contributions are welcome!

**Comment by WangJincheng4869** [comment]
I also encountered the same problem, I don't know if it's the same reason, but I left my picture here.
[image](https://github.com/WangJincheng4869/fanKuiWenJian/blob/main/%E5%9B%BE%E5%B1%82%200%402x.webp)

**Comment by pvanek** [comment]
I can offer set of affected packages as well

**Comment by haraldk** [comment]
Fixed via #1315
