### ISSUE TITLE
Unable to read JPEG image: "IllegalArgumentException: bandOffsets.length is wrong!"

### ISSUE THREAD

**Issue by mjball** [haraldk/TwelveMonkeys#99]
I get this exception trying to read one of the JPEG files I'm trying to process:

```
Caused by: java.lang.IllegalArgumentException: bandOffsets.length is wrong!
	at javax.imageio.ImageTypeSpecifier$Interleaved.<init>(ImageTypeSpecifier.java:286)
	at javax.imageio.ImageTypeSpecifier.createInterleaved(ImageTypeSpecifier.java:399)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageTypes(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at com.hubspot.imageutils.ImageUtils.getImage(ImageUtils.java:293)
	at com.hubspot.imageutils.ImageUtils.resizeImage(ImageUtils.java:
```

![image](https://cloud.githubusercontent.com/assets/378111/6381053/649f7d56-bd0c-11e4-9b5f-993260b9956b.png)

Original: http://pbs.twimg.com/profile_images/1877700001/logo.jpg

Help?

**Comment by haraldk** [comment]
Hi Mike,

Thanks for reporting!

This image is so seriously damaged. Cool. ;-)
Do you happen to know what software created it?

- The image has a JFIF segment. JFIF only allows 1 or 3 components, encoded as Y (intensity/gray) or YCbCr (converted from RGB).
- The SOF segment has 4 components, with component IDs 69, 77, 89, 75 (ASCII: C,M,Y,K) indicating CMYK color space. This means the JFIF segment is bogus.
- The image has an Adobe segment, which could clarify what the extra channel is for, but it doesn't say...
- The image has an RGB color profile... This should mean the data is ARGB (it's not).

The last point is what causes the exception you see, as I try to create an `ImageTypeSpecifier` with four bands and no alpha, but the color space has only 3 color components (RGB).

I'll investigate...


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
All right!

Should be fixed in 34cd913216d78e6ced9a32113c9212d3e7ffa765. Will be release as part of 3.1 very soon. In the mean time, you can build the latest version from source. :-)

Best regards,

-- 
Harald K

**Comment by mjball** [comment]
You're awesome, thanks! Can't wait for 3.1. As for the original source of the image: I tweeted at [the company](https://twitter.com/EGPServices) but I don't have high hopes for getting a real answer.

**Comment by mjball** [comment]
When you say "very soon" are you looking at releasing 3.1 in days or weeks?

**Comment by haraldk** [comment]
Good question! :-)

I'm hoping days, but as I work on this project only in my spare time, I'm not making any promises.

If you need this fix ASAP, I'd recommend building latest from source.


Best regards,

-- 
Harald K
